/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.CommonSwapResponseFees;
import com.coinbase.cdp.openapi.model.CommonSwapResponseIssues;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * CommonSwapResponse
 */
@JsonPropertyOrder({
  CommonSwapResponse.JSON_PROPERTY_BLOCK_NUMBER,
  CommonSwapResponse.JSON_PROPERTY_TO_AMOUNT,
  CommonSwapResponse.JSON_PROPERTY_TO_TOKEN,
  CommonSwapResponse.JSON_PROPERTY_FEES,
  CommonSwapResponse.JSON_PROPERTY_ISSUES,
  CommonSwapResponse.JSON_PROPERTY_LIQUIDITY_AVAILABLE,
  CommonSwapResponse.JSON_PROPERTY_MIN_TO_AMOUNT,
  CommonSwapResponse.JSON_PROPERTY_FROM_AMOUNT,
  CommonSwapResponse.JSON_PROPERTY_FROM_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CommonSwapResponse {
  public static final String JSON_PROPERTY_BLOCK_NUMBER = "blockNumber";
  @jakarta.annotation.Nonnull
  private String blockNumber;

  public static final String JSON_PROPERTY_TO_AMOUNT = "toAmount";
  @jakarta.annotation.Nonnull
  private String toAmount;

  public static final String JSON_PROPERTY_TO_TOKEN = "toToken";
  @jakarta.annotation.Nonnull
  private String toToken;

  public static final String JSON_PROPERTY_FEES = "fees";
  @jakarta.annotation.Nonnull
  private CommonSwapResponseFees fees;

  public static final String JSON_PROPERTY_ISSUES = "issues";
  @jakarta.annotation.Nonnull
  private CommonSwapResponseIssues issues;

  /**
   * Whether sufficient liquidity is available to settle the swap. All other fields in the response will be empty if this is false.
   */
  public enum LiquidityAvailableEnum {
    TRUE(Boolean.valueOf("true"));

    private Boolean value;

    LiquidityAvailableEnum(Boolean value) {
      this.value = value;
    }

    @JsonValue
    public Boolean getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LiquidityAvailableEnum fromValue(Boolean value) {
      for (LiquidityAvailableEnum b : LiquidityAvailableEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LIQUIDITY_AVAILABLE = "liquidityAvailable";
  @jakarta.annotation.Nonnull
  private LiquidityAvailableEnum liquidityAvailable;

  public static final String JSON_PROPERTY_MIN_TO_AMOUNT = "minToAmount";
  @jakarta.annotation.Nonnull
  private String minToAmount;

  public static final String JSON_PROPERTY_FROM_AMOUNT = "fromAmount";
  @jakarta.annotation.Nonnull
  private String fromAmount;

  public static final String JSON_PROPERTY_FROM_TOKEN = "fromToken";
  @jakarta.annotation.Nonnull
  private String fromToken;

  public CommonSwapResponse() { 
  }

  public CommonSwapResponse blockNumber(@jakarta.annotation.Nonnull String blockNumber) {
    this.blockNumber = blockNumber;
    return this;
  }

  /**
   * The block number at which the liquidity conditions were examined.
   * @return blockNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BLOCK_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBlockNumber() {
    return blockNumber;
  }


  @JsonProperty(JSON_PROPERTY_BLOCK_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBlockNumber(@jakarta.annotation.Nonnull String blockNumber) {
    this.blockNumber = blockNumber;
  }


  public CommonSwapResponse toAmount(@jakarta.annotation.Nonnull String toAmount) {
    this.toAmount = toAmount;
    return this;
  }

  /**
   * The amount of the &#x60;toToken&#x60; that will be received in atomic units of the &#x60;toToken&#x60;. For example, &#x60;1000000000000000000&#x60; when receiving ETH equates to 1 ETH, &#x60;1000000&#x60; when receiving USDC equates to 1 USDC, etc.
   * @return toAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getToAmount() {
    return toAmount;
  }


  @JsonProperty(JSON_PROPERTY_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToAmount(@jakarta.annotation.Nonnull String toAmount) {
    this.toAmount = toAmount;
  }


  public CommonSwapResponse toToken(@jakarta.annotation.Nonnull String toToken) {
    this.toToken = toToken;
    return this;
  }

  /**
   * The 0x-prefixed contract address of the token that will be received.
   * @return toToken
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TO_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getToToken() {
    return toToken;
  }


  @JsonProperty(JSON_PROPERTY_TO_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToToken(@jakarta.annotation.Nonnull String toToken) {
    this.toToken = toToken;
  }


  public CommonSwapResponse fees(@jakarta.annotation.Nonnull CommonSwapResponseFees fees) {
    this.fees = fees;
    return this;
  }

  /**
   * Get fees
   * @return fees
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CommonSwapResponseFees getFees() {
    return fees;
  }


  @JsonProperty(JSON_PROPERTY_FEES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFees(@jakarta.annotation.Nonnull CommonSwapResponseFees fees) {
    this.fees = fees;
  }


  public CommonSwapResponse issues(@jakarta.annotation.Nonnull CommonSwapResponseIssues issues) {
    this.issues = issues;
    return this;
  }

  /**
   * Get issues
   * @return issues
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ISSUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CommonSwapResponseIssues getIssues() {
    return issues;
  }


  @JsonProperty(JSON_PROPERTY_ISSUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssues(@jakarta.annotation.Nonnull CommonSwapResponseIssues issues) {
    this.issues = issues;
  }


  public CommonSwapResponse liquidityAvailable(@jakarta.annotation.Nonnull LiquidityAvailableEnum liquidityAvailable) {
    this.liquidityAvailable = liquidityAvailable;
    return this;
  }

  /**
   * Whether sufficient liquidity is available to settle the swap. All other fields in the response will be empty if this is false.
   * @return liquidityAvailable
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIQUIDITY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LiquidityAvailableEnum getLiquidityAvailable() {
    return liquidityAvailable;
  }


  @JsonProperty(JSON_PROPERTY_LIQUIDITY_AVAILABLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLiquidityAvailable(@jakarta.annotation.Nonnull LiquidityAvailableEnum liquidityAvailable) {
    this.liquidityAvailable = liquidityAvailable;
  }


  public CommonSwapResponse minToAmount(@jakarta.annotation.Nonnull String minToAmount) {
    this.minToAmount = minToAmount;
    return this;
  }

  /**
   * The minimum amount of the &#x60;toToken&#x60; that must be received for the swap to succeed, in atomic units of the &#x60;toToken&#x60;.  For example, &#x60;1000000000000000000&#x60; when receiving ETH equates to 1 ETH, &#x60;1000000&#x60; when receiving USDC equates to 1 USDC, etc. This value is influenced by the &#x60;slippageBps&#x60; parameter.
   * @return minToAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MIN_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMinToAmount() {
    return minToAmount;
  }


  @JsonProperty(JSON_PROPERTY_MIN_TO_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinToAmount(@jakarta.annotation.Nonnull String minToAmount) {
    this.minToAmount = minToAmount;
  }


  public CommonSwapResponse fromAmount(@jakarta.annotation.Nonnull String fromAmount) {
    this.fromAmount = fromAmount;
    return this;
  }

  /**
   * The amount of the &#x60;fromToken&#x60; that will be sent in this swap, in atomic units of the &#x60;fromToken&#x60;. For example, &#x60;1000000000000000000&#x60; when sending ETH equates to 1 ETH, &#x60;1000000&#x60; when sending USDC equates to 1 USDC, etc.
   * @return fromAmount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFromAmount() {
    return fromAmount;
  }


  @JsonProperty(JSON_PROPERTY_FROM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromAmount(@jakarta.annotation.Nonnull String fromAmount) {
    this.fromAmount = fromAmount;
  }


  public CommonSwapResponse fromToken(@jakarta.annotation.Nonnull String fromToken) {
    this.fromToken = fromToken;
    return this;
  }

  /**
   * The 0x-prefixed contract address of the token that will be sent.
   * @return fromToken
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFromToken() {
    return fromToken;
  }


  @JsonProperty(JSON_PROPERTY_FROM_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromToken(@jakarta.annotation.Nonnull String fromToken) {
    this.fromToken = fromToken;
  }


  /**
   * Return true if this CommonSwapResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonSwapResponse commonSwapResponse = (CommonSwapResponse) o;
    return Objects.equals(this.blockNumber, commonSwapResponse.blockNumber) &&
        Objects.equals(this.toAmount, commonSwapResponse.toAmount) &&
        Objects.equals(this.toToken, commonSwapResponse.toToken) &&
        Objects.equals(this.fees, commonSwapResponse.fees) &&
        Objects.equals(this.issues, commonSwapResponse.issues) &&
        Objects.equals(this.liquidityAvailable, commonSwapResponse.liquidityAvailable) &&
        Objects.equals(this.minToAmount, commonSwapResponse.minToAmount) &&
        Objects.equals(this.fromAmount, commonSwapResponse.fromAmount) &&
        Objects.equals(this.fromToken, commonSwapResponse.fromToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockNumber, toAmount, toToken, fees, issues, liquidityAvailable, minToAmount, fromAmount, fromToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonSwapResponse {\n");
    sb.append("    blockNumber: ").append(toIndentedString(blockNumber)).append("\n");
    sb.append("    toAmount: ").append(toIndentedString(toAmount)).append("\n");
    sb.append("    toToken: ").append(toIndentedString(toToken)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    issues: ").append(toIndentedString(issues)).append("\n");
    sb.append("    liquidityAvailable: ").append(toIndentedString(liquidityAvailable)).append("\n");
    sb.append("    minToAmount: ").append(toIndentedString(minToAmount)).append("\n");
    sb.append("    fromAmount: ").append(toIndentedString(fromAmount)).append("\n");
    sb.append("    fromToken: ").append(toIndentedString(fromToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `blockNumber` to the URL query string
    if (getBlockNumber() != null) {
      joiner.add(String.format("%sblockNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getBlockNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `toAmount` to the URL query string
    if (getToAmount() != null) {
      joiner.add(String.format("%stoAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getToAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `toToken` to the URL query string
    if (getToToken() != null) {
      joiner.add(String.format("%stoToken%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getToToken()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fees` to the URL query string
    if (getFees() != null) {
      joiner.add(getFees().toUrlQueryString(prefix + "fees" + suffix));
    }

    // add `issues` to the URL query string
    if (getIssues() != null) {
      joiner.add(getIssues().toUrlQueryString(prefix + "issues" + suffix));
    }

    // add `liquidityAvailable` to the URL query string
    if (getLiquidityAvailable() != null) {
      joiner.add(String.format("%sliquidityAvailable%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getLiquidityAvailable()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `minToAmount` to the URL query string
    if (getMinToAmount() != null) {
      joiner.add(String.format("%sminToAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMinToAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fromAmount` to the URL query string
    if (getFromAmount() != null) {
      joiner.add(String.format("%sfromAmount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFromAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `fromToken` to the URL query string
    if (getFromToken() != null) {
      joiner.add(String.format("%sfromToken%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFromToken()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private CommonSwapResponse instance;

    public Builder() {
      this(new CommonSwapResponse());
    }

    protected Builder(CommonSwapResponse instance) {
      this.instance = instance;
    }

    public CommonSwapResponse.Builder blockNumber(String blockNumber) {
      this.instance.blockNumber = blockNumber;
      return this;
    }
    public CommonSwapResponse.Builder toAmount(String toAmount) {
      this.instance.toAmount = toAmount;
      return this;
    }
    public CommonSwapResponse.Builder toToken(String toToken) {
      this.instance.toToken = toToken;
      return this;
    }
    public CommonSwapResponse.Builder fees(CommonSwapResponseFees fees) {
      this.instance.fees = fees;
      return this;
    }
    public CommonSwapResponse.Builder issues(CommonSwapResponseIssues issues) {
      this.instance.issues = issues;
      return this;
    }
    public CommonSwapResponse.Builder liquidityAvailable(LiquidityAvailableEnum liquidityAvailable) {
      this.instance.liquidityAvailable = liquidityAvailable;
      return this;
    }
    public CommonSwapResponse.Builder minToAmount(String minToAmount) {
      this.instance.minToAmount = minToAmount;
      return this;
    }
    public CommonSwapResponse.Builder fromAmount(String fromAmount) {
      this.instance.fromAmount = fromAmount;
      return this;
    }
    public CommonSwapResponse.Builder fromToken(String fromToken) {
      this.instance.fromToken = fromToken;
      return this;
    }


    /**
    * returns a built CommonSwapResponse instance.
    *
    * The builder is not reusable.
    */
    public CommonSwapResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CommonSwapResponse.Builder builder() {
    return new CommonSwapResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CommonSwapResponse.Builder toBuilder() {
    return new CommonSwapResponse.Builder()
      .blockNumber(getBlockNumber())
      .toAmount(getToAmount())
      .toToken(getToToken())
      .fees(getFees())
      .issues(getIssues())
      .liquidityAvailable(getLiquidityAvailable())
      .minToAmount(getMinToAmount())
      .fromAmount(getFromAmount())
      .fromToken(getFromToken());
  }

}

