/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.EIP712Message;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * The approval object which contains the necessary fields to submit an approval for this transaction. Null if the &#x60;fromToken&#x60; is the native token or the transaction is a native token wrap / unwrap.
 */
@JsonPropertyOrder({
  CreateSwapQuoteResponseAllOfPermit2.JSON_PROPERTY_HASH,
  CreateSwapQuoteResponseAllOfPermit2.JSON_PROPERTY_EIP712
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class CreateSwapQuoteResponseAllOfPermit2 {
  public static final String JSON_PROPERTY_HASH = "hash";
  @jakarta.annotation.Nonnull
  private String hash;

  public static final String JSON_PROPERTY_EIP712 = "eip712";
  @jakarta.annotation.Nonnull
  private EIP712Message eip712;

  public CreateSwapQuoteResponseAllOfPermit2() { 
  }

  public CreateSwapQuoteResponseAllOfPermit2 hash(@jakarta.annotation.Nonnull String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * The hash for the approval according to [EIP-712](https://eips.ethereum.org/EIPS/eip-712). Computing the hash of the &#x60;eip712&#x60; field should match the value of this field.
   * @return hash
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHash() {
    return hash;
  }


  @JsonProperty(JSON_PROPERTY_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHash(@jakarta.annotation.Nonnull String hash) {
    this.hash = hash;
  }


  public CreateSwapQuoteResponseAllOfPermit2 eip712(@jakarta.annotation.Nonnull EIP712Message eip712) {
    this.eip712 = eip712;
    return this;
  }

  /**
   * Get eip712
   * @return eip712
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EIP712)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EIP712Message getEip712() {
    return eip712;
  }


  @JsonProperty(JSON_PROPERTY_EIP712)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEip712(@jakarta.annotation.Nonnull EIP712Message eip712) {
    this.eip712 = eip712;
  }


  /**
   * Return true if this CreateSwapQuoteResponse_allOf_permit2 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSwapQuoteResponseAllOfPermit2 createSwapQuoteResponseAllOfPermit2 = (CreateSwapQuoteResponseAllOfPermit2) o;
    return Objects.equals(this.hash, createSwapQuoteResponseAllOfPermit2.hash) &&
        Objects.equals(this.eip712, createSwapQuoteResponseAllOfPermit2.eip712);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, eip712);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSwapQuoteResponseAllOfPermit2 {\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    eip712: ").append(toIndentedString(eip712)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `hash` to the URL query string
    if (getHash() != null) {
      joiner.add(String.format("%shash%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getHash()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `eip712` to the URL query string
    if (getEip712() != null) {
      joiner.add(getEip712().toUrlQueryString(prefix + "eip712" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private CreateSwapQuoteResponseAllOfPermit2 instance;

    public Builder() {
      this(new CreateSwapQuoteResponseAllOfPermit2());
    }

    protected Builder(CreateSwapQuoteResponseAllOfPermit2 instance) {
      this.instance = instance;
    }

    public CreateSwapQuoteResponseAllOfPermit2.Builder hash(String hash) {
      this.instance.hash = hash;
      return this;
    }
    public CreateSwapQuoteResponseAllOfPermit2.Builder eip712(EIP712Message eip712) {
      this.instance.eip712 = eip712;
      return this;
    }


    /**
    * returns a built CreateSwapQuoteResponseAllOfPermit2 instance.
    *
    * The builder is not reusable.
    */
    public CreateSwapQuoteResponseAllOfPermit2 build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CreateSwapQuoteResponseAllOfPermit2.Builder builder() {
    return new CreateSwapQuoteResponseAllOfPermit2.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CreateSwapQuoteResponseAllOfPermit2.Builder toBuilder() {
    return new CreateSwapQuoteResponseAllOfPermit2.Builder()
      .hash(getHash())
      .eip712(getEip712());
  }

}

