/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * Information about an end user who authenticates using a JWT issued by the developer.
 */
@JsonPropertyOrder({
  DeveloperJWTAuthentication.JSON_PROPERTY_TYPE,
  DeveloperJWTAuthentication.JSON_PROPERTY_KID,
  DeveloperJWTAuthentication.JSON_PROPERTY_SUB
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class DeveloperJWTAuthentication {
  /**
   * The type of authentication information.
   */
  public enum TypeEnum {
    JWT(String.valueOf("jwt"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_KID = "kid";
  @jakarta.annotation.Nonnull
  private String kid;

  public static final String JSON_PROPERTY_SUB = "sub";
  @jakarta.annotation.Nonnull
  private String sub;

  public DeveloperJWTAuthentication() { 
  }

  public DeveloperJWTAuthentication type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of authentication information.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public DeveloperJWTAuthentication kid(@jakarta.annotation.Nonnull String kid) {
    this.kid = kid;
    return this;
  }

  /**
   * The key ID of the JWK used to sign the JWT.
   * @return kid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKid() {
    return kid;
  }


  @JsonProperty(JSON_PROPERTY_KID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKid(@jakarta.annotation.Nonnull String kid) {
    this.kid = kid;
  }


  public DeveloperJWTAuthentication sub(@jakarta.annotation.Nonnull String sub) {
    this.sub = sub;
    return this;
  }

  /**
   * The unique identifier for the end user that is captured in the &#x60;sub&#x60; claim of the JWT.
   * @return sub
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSub() {
    return sub;
  }


  @JsonProperty(JSON_PROPERTY_SUB)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSub(@jakarta.annotation.Nonnull String sub) {
    this.sub = sub;
  }


  /**
   * Return true if this DeveloperJWTAuthentication object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeveloperJWTAuthentication developerJWTAuthentication = (DeveloperJWTAuthentication) o;
    return Objects.equals(this.type, developerJWTAuthentication.type) &&
        Objects.equals(this.kid, developerJWTAuthentication.kid) &&
        Objects.equals(this.sub, developerJWTAuthentication.sub);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, kid, sub);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeveloperJWTAuthentication {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    kid: ").append(toIndentedString(kid)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `kid` to the URL query string
    if (getKid() != null) {
      joiner.add(String.format("%skid%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getKid()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `sub` to the URL query string
    if (getSub() != null) {
      joiner.add(String.format("%ssub%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSub()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private DeveloperJWTAuthentication instance;

    public Builder() {
      this(new DeveloperJWTAuthentication());
    }

    protected Builder(DeveloperJWTAuthentication instance) {
      this.instance = instance;
    }

    public DeveloperJWTAuthentication.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public DeveloperJWTAuthentication.Builder kid(String kid) {
      this.instance.kid = kid;
      return this;
    }
    public DeveloperJWTAuthentication.Builder sub(String sub) {
      this.instance.sub = sub;
      return this;
    }


    /**
    * returns a built DeveloperJWTAuthentication instance.
    *
    * The builder is not reusable.
    */
    public DeveloperJWTAuthentication build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static DeveloperJWTAuthentication.Builder builder() {
    return new DeveloperJWTAuthentication.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public DeveloperJWTAuthentication.Builder toBuilder() {
    return new DeveloperJWTAuthentication.Builder()
      .type(getType())
      .kid(getKid())
      .sub(getSub());
  }

}

