/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * EvmDataParameterConditionList
 */
@JsonPropertyOrder({
  EvmDataParameterConditionList.JSON_PROPERTY_NAME,
  EvmDataParameterConditionList.JSON_PROPERTY_OPERATOR,
  EvmDataParameterConditionList.JSON_PROPERTY_VALUES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class EvmDataParameterConditionList {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  /**
   * The operator to use for the comparison. The value resolved at the &#x60;name&#x60; will be on the left-hand side of the operator, and the &#x60;values&#x60; field will be on the right-hand side.
   */
  public enum OperatorEnum {
    IN(String.valueOf("in")),
    
    NOT_IN(String.valueOf("not in"));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @jakarta.annotation.Nonnull
  private OperatorEnum operator;

  public static final String JSON_PROPERTY_VALUES = "values";
  @jakarta.annotation.Nonnull
  private List<String> values = new ArrayList<>();

  public EvmDataParameterConditionList() { 
  }

  public EvmDataParameterConditionList name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the parameter to check against a transaction&#39;s calldata. If name is unknown, or is not named, you may supply an array index, e.g., &#x60;0&#x60; for first parameter.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public EvmDataParameterConditionList operator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * The operator to use for the comparison. The value resolved at the &#x60;name&#x60; will be on the left-hand side of the operator, and the &#x60;values&#x60; field will be on the right-hand side.
   * @return operator
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
  }


  public EvmDataParameterConditionList values(@jakarta.annotation.Nonnull List<String> values) {
    this.values = values;
    return this;
  }

  public EvmDataParameterConditionList addValuesItem(String valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

  /**
   * Values to compare against the resolved &#x60;name&#x60; value. All values are encoded as strings. Refer to the table in the documentation for how values should be encoded, and which operators are supported for each type.
   * @return values
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValues(@jakarta.annotation.Nonnull List<String> values) {
    this.values = values;
  }


  /**
   * Return true if this EvmDataParameterConditionList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvmDataParameterConditionList evmDataParameterConditionList = (EvmDataParameterConditionList) o;
    return Objects.equals(this.name, evmDataParameterConditionList.name) &&
        Objects.equals(this.operator, evmDataParameterConditionList.operator) &&
        Objects.equals(this.values, evmDataParameterConditionList.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, operator, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvmDataParameterConditionList {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format("%soperator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOperator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `values` to the URL query string
    if (getValues() != null) {
      for (int i = 0; i < getValues().size(); i++) {
        joiner.add(String.format("%svalues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getValues().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private EvmDataParameterConditionList instance;

    public Builder() {
      this(new EvmDataParameterConditionList());
    }

    protected Builder(EvmDataParameterConditionList instance) {
      this.instance = instance;
    }

    public EvmDataParameterConditionList.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public EvmDataParameterConditionList.Builder operator(OperatorEnum operator) {
      this.instance.operator = operator;
      return this;
    }
    public EvmDataParameterConditionList.Builder values(List<String> values) {
      this.instance.values = values;
      return this;
    }


    /**
    * returns a built EvmDataParameterConditionList instance.
    *
    * The builder is not reusable.
    */
    public EvmDataParameterConditionList build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static EvmDataParameterConditionList.Builder builder() {
    return new EvmDataParameterConditionList.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public EvmDataParameterConditionList.Builder toBuilder() {
    return new EvmDataParameterConditionList.Builder()
      .name(getName())
      .operator(getOperator())
      .values(getValues());
  }

}

