/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.OnrampOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * GetOnrampOrderById200Response
 */
@JsonPropertyOrder({
  GetOnrampOrderById200Response.JSON_PROPERTY_ORDER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetOnrampOrderById200Response {
  public static final String JSON_PROPERTY_ORDER = "order";
  @jakarta.annotation.Nonnull
  private OnrampOrder order;

  public GetOnrampOrderById200Response() { 
  }

  public GetOnrampOrderById200Response order(@jakarta.annotation.Nonnull OnrampOrder order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OnrampOrder getOrder() {
    return order;
  }


  @JsonProperty(JSON_PROPERTY_ORDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrder(@jakarta.annotation.Nonnull OnrampOrder order) {
    this.order = order;
  }


  /**
   * Return true if this getOnrampOrderById_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOnrampOrderById200Response getOnrampOrderById200Response = (GetOnrampOrderById200Response) o;
    return Objects.equals(this.order, getOnrampOrderById200Response.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOnrampOrderById200Response {\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `order` to the URL query string
    if (getOrder() != null) {
      joiner.add(getOrder().toUrlQueryString(prefix + "order" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private GetOnrampOrderById200Response instance;

    public Builder() {
      this(new GetOnrampOrderById200Response());
    }

    protected Builder(GetOnrampOrderById200Response instance) {
      this.instance = instance;
    }

    public GetOnrampOrderById200Response.Builder order(OnrampOrder order) {
      this.instance.order = order;
      return this;
    }


    /**
    * returns a built GetOnrampOrderById200Response instance.
    *
    * The builder is not reusable.
    */
    public GetOnrampOrderById200Response build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static GetOnrampOrderById200Response.Builder builder() {
    return new GetOnrampOrderById200Response.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public GetOnrampOrderById200Response.Builder toBuilder() {
    return new GetOnrampOrderById200Response.Builder()
      .order(getOrder());
  }

}

