/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.OnrampUserLimit;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * GetOnrampUserLimits200Response
 */
@JsonPropertyOrder({
  GetOnrampUserLimits200Response.JSON_PROPERTY_LIMITS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetOnrampUserLimits200Response {
  public static final String JSON_PROPERTY_LIMITS = "limits";
  @jakarta.annotation.Nonnull
  private List<OnrampUserLimit> limits = new ArrayList<>();

  public GetOnrampUserLimits200Response() { 
  }

  public GetOnrampUserLimits200Response limits(@jakarta.annotation.Nonnull List<OnrampUserLimit> limits) {
    this.limits = limits;
    return this;
  }

  public GetOnrampUserLimits200Response addLimitsItem(OnrampUserLimit limitsItem) {
    if (this.limits == null) {
      this.limits = new ArrayList<>();
    }
    this.limits.add(limitsItem);
    return this;
  }

  /**
   * The list of limits applicable to the user.
   * @return limits
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LIMITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<OnrampUserLimit> getLimits() {
    return limits;
  }


  @JsonProperty(JSON_PROPERTY_LIMITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimits(@jakarta.annotation.Nonnull List<OnrampUserLimit> limits) {
    this.limits = limits;
  }


  /**
   * Return true if this getOnrampUserLimits_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOnrampUserLimits200Response getOnrampUserLimits200Response = (GetOnrampUserLimits200Response) o;
    return Objects.equals(this.limits, getOnrampUserLimits200Response.limits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOnrampUserLimits200Response {\n");
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `limits` to the URL query string
    if (getLimits() != null) {
      for (int i = 0; i < getLimits().size(); i++) {
        if (getLimits().get(i) != null) {
          joiner.add(getLimits().get(i).toUrlQueryString(String.format("%slimits%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private GetOnrampUserLimits200Response instance;

    public Builder() {
      this(new GetOnrampUserLimits200Response());
    }

    protected Builder(GetOnrampUserLimits200Response instance) {
      this.instance = instance;
    }

    public GetOnrampUserLimits200Response.Builder limits(List<OnrampUserLimit> limits) {
      this.instance.limits = limits;
      return this;
    }


    /**
    * returns a built GetOnrampUserLimits200Response instance.
    *
    * The builder is not reusable.
    */
    public GetOnrampUserLimits200Response build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static GetOnrampUserLimits200Response.Builder builder() {
    return new GetOnrampUserLimits200Response.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public GetOnrampUserLimits200Response.Builder toBuilder() {
    return new GetOnrampUserLimits200Response.Builder()
      .limits(getLimits());
  }

}

