/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * ImportSolanaAccountRequest
 */
@JsonPropertyOrder({
  ImportSolanaAccountRequest.JSON_PROPERTY_ENCRYPTED_PRIVATE_KEY,
  ImportSolanaAccountRequest.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class ImportSolanaAccountRequest {
  public static final String JSON_PROPERTY_ENCRYPTED_PRIVATE_KEY = "encryptedPrivateKey";
  @jakarta.annotation.Nonnull
  private String encryptedPrivateKey;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public ImportSolanaAccountRequest() { 
  }

  public ImportSolanaAccountRequest encryptedPrivateKey(@jakarta.annotation.Nonnull String encryptedPrivateKey) {
    this.encryptedPrivateKey = encryptedPrivateKey;
    return this;
  }

  /**
   * The base64-encoded, encrypted 32-byte private key of the Solana account. The private key must be encrypted using the CDP SDK&#39;s encryption scheme.
   * @return encryptedPrivateKey
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENCRYPTED_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEncryptedPrivateKey() {
    return encryptedPrivateKey;
  }


  @JsonProperty(JSON_PROPERTY_ENCRYPTED_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEncryptedPrivateKey(@jakarta.annotation.Nonnull String encryptedPrivateKey) {
    this.encryptedPrivateKey = encryptedPrivateKey;
  }


  public ImportSolanaAccountRequest name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * An optional name for the account. Account names can consist of alphanumeric characters and hyphens, and be between 2 and 36 characters long. Account names must be unique across all EVM accounts in the developer&#39;s CDP Project.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  /**
   * Return true if this importSolanaAccount_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImportSolanaAccountRequest importSolanaAccountRequest = (ImportSolanaAccountRequest) o;
    return Objects.equals(this.encryptedPrivateKey, importSolanaAccountRequest.encryptedPrivateKey) &&
        Objects.equals(this.name, importSolanaAccountRequest.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encryptedPrivateKey, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImportSolanaAccountRequest {\n");
    sb.append("    encryptedPrivateKey: ").append(toIndentedString(encryptedPrivateKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `encryptedPrivateKey` to the URL query string
    if (getEncryptedPrivateKey() != null) {
      joiner.add(String.format("%sencryptedPrivateKey%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEncryptedPrivateKey()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private ImportSolanaAccountRequest instance;

    public Builder() {
      this(new ImportSolanaAccountRequest());
    }

    protected Builder(ImportSolanaAccountRequest instance) {
      this.instance = instance;
    }

    public ImportSolanaAccountRequest.Builder encryptedPrivateKey(String encryptedPrivateKey) {
      this.instance.encryptedPrivateKey = encryptedPrivateKey;
      return this;
    }
    public ImportSolanaAccountRequest.Builder name(String name) {
      this.instance.name = name;
      return this;
    }


    /**
    * returns a built ImportSolanaAccountRequest instance.
    *
    * The builder is not reusable.
    */
    public ImportSolanaAccountRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ImportSolanaAccountRequest.Builder builder() {
    return new ImportSolanaAccountRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ImportSolanaAccountRequest.Builder toBuilder() {
    return new ImportSolanaAccountRequest.Builder()
      .encryptedPrivateKey(getEncryptedPrivateKey())
      .name(getName());
  }

}

