/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * An object containing information about the end user&#39;s SMS MFA enrollment.
 */
@JsonPropertyOrder({
  MFAMethodsSms.JSON_PROPERTY_ENROLLED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class MFAMethodsSms {
  public static final String JSON_PROPERTY_ENROLLED_AT = "enrolledAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime enrolledAt;

  public MFAMethodsSms() { 
  }

  public MFAMethodsSms enrolledAt(@jakarta.annotation.Nonnull OffsetDateTime enrolledAt) {
    this.enrolledAt = enrolledAt;
    return this;
  }

  /**
   * The date and time when the method was enrolled, in ISO 8601 format.
   * @return enrolledAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ENROLLED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getEnrolledAt() {
    return enrolledAt;
  }


  @JsonProperty(JSON_PROPERTY_ENROLLED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnrolledAt(@jakarta.annotation.Nonnull OffsetDateTime enrolledAt) {
    this.enrolledAt = enrolledAt;
  }


  /**
   * Return true if this MFAMethods_sms object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MFAMethodsSms mfAMethodsSms = (MFAMethodsSms) o;
    return Objects.equals(this.enrolledAt, mfAMethodsSms.enrolledAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enrolledAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MFAMethodsSms {\n");
    sb.append("    enrolledAt: ").append(toIndentedString(enrolledAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enrolledAt` to the URL query string
    if (getEnrolledAt() != null) {
      joiner.add(String.format("%senrolledAt%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getEnrolledAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private MFAMethodsSms instance;

    public Builder() {
      this(new MFAMethodsSms());
    }

    protected Builder(MFAMethodsSms instance) {
      this.instance = instance;
    }

    public MFAMethodsSms.Builder enrolledAt(OffsetDateTime enrolledAt) {
      this.instance.enrolledAt = enrolledAt;
      return this;
    }


    /**
    * returns a built MFAMethodsSms instance.
    *
    * The builder is not reusable.
    */
    public MFAMethodsSms build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MFAMethodsSms.Builder builder() {
    return new MFAMethodsSms.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MFAMethodsSms.Builder toBuilder() {
    return new MFAMethodsSms.Builder()
      .enrolledAt(getEnrolledAt());
  }

}

