/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.SpendPermissionNetwork;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * Request parameters for revoking a Spend Permission.
 */
@JsonPropertyOrder({
  RevokeSpendPermissionRequest.JSON_PROPERTY_NETWORK,
  RevokeSpendPermissionRequest.JSON_PROPERTY_PERMISSION_HASH,
  RevokeSpendPermissionRequest.JSON_PROPERTY_PAYMASTER_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class RevokeSpendPermissionRequest {
  public static final String JSON_PROPERTY_NETWORK = "network";
  @jakarta.annotation.Nonnull
  private SpendPermissionNetwork network;

  public static final String JSON_PROPERTY_PERMISSION_HASH = "permissionHash";
  @jakarta.annotation.Nonnull
  private String permissionHash;

  public static final String JSON_PROPERTY_PAYMASTER_URL = "paymasterUrl";
  @jakarta.annotation.Nullable
  private URI paymasterUrl;

  public RevokeSpendPermissionRequest() { 
  }

  public RevokeSpendPermissionRequest network(@jakarta.annotation.Nonnull SpendPermissionNetwork network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SpendPermissionNetwork getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(@jakarta.annotation.Nonnull SpendPermissionNetwork network) {
    this.network = network;
  }


  public RevokeSpendPermissionRequest permissionHash(@jakarta.annotation.Nonnull String permissionHash) {
    this.permissionHash = permissionHash;
    return this;
  }

  /**
   * The hash of the spend permission to revoke.
   * @return permissionHash
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PERMISSION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPermissionHash() {
    return permissionHash;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSION_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissionHash(@jakarta.annotation.Nonnull String permissionHash) {
    this.permissionHash = permissionHash;
  }


  public RevokeSpendPermissionRequest paymasterUrl(@jakarta.annotation.Nullable URI paymasterUrl) {
    this.paymasterUrl = paymasterUrl;
    return this;
  }

  /**
   * The paymaster URL of the spend permission.
   * @return paymasterUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMASTER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getPaymasterUrl() {
    return paymasterUrl;
  }


  @JsonProperty(JSON_PROPERTY_PAYMASTER_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymasterUrl(@jakarta.annotation.Nullable URI paymasterUrl) {
    this.paymasterUrl = paymasterUrl;
  }


  /**
   * Return true if this RevokeSpendPermissionRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RevokeSpendPermissionRequest revokeSpendPermissionRequest = (RevokeSpendPermissionRequest) o;
    return Objects.equals(this.network, revokeSpendPermissionRequest.network) &&
        Objects.equals(this.permissionHash, revokeSpendPermissionRequest.permissionHash) &&
        Objects.equals(this.paymasterUrl, revokeSpendPermissionRequest.paymasterUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(network, permissionHash, paymasterUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RevokeSpendPermissionRequest {\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    permissionHash: ").append(toIndentedString(permissionHash)).append("\n");
    sb.append("    paymasterUrl: ").append(toIndentedString(paymasterUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNetwork()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `permissionHash` to the URL query string
    if (getPermissionHash() != null) {
      joiner.add(String.format("%spermissionHash%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPermissionHash()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `paymasterUrl` to the URL query string
    if (getPaymasterUrl() != null) {
      joiner.add(String.format("%spaymasterUrl%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPaymasterUrl()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private RevokeSpendPermissionRequest instance;

    public Builder() {
      this(new RevokeSpendPermissionRequest());
    }

    protected Builder(RevokeSpendPermissionRequest instance) {
      this.instance = instance;
    }

    public RevokeSpendPermissionRequest.Builder network(SpendPermissionNetwork network) {
      this.instance.network = network;
      return this;
    }
    public RevokeSpendPermissionRequest.Builder permissionHash(String permissionHash) {
      this.instance.permissionHash = permissionHash;
      return this;
    }
    public RevokeSpendPermissionRequest.Builder paymasterUrl(URI paymasterUrl) {
      this.instance.paymasterUrl = paymasterUrl;
      return this;
    }


    /**
    * returns a built RevokeSpendPermissionRequest instance.
    *
    * The builder is not reusable.
    */
    public RevokeSpendPermissionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static RevokeSpendPermissionRequest.Builder builder() {
    return new RevokeSpendPermissionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public RevokeSpendPermissionRequest.Builder toBuilder() {
    return new RevokeSpendPermissionRequest.Builder()
      .network(getNetwork())
      .permissionHash(getPermissionHash())
      .paymasterUrl(getPaymasterUrl());
  }

}

