/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.PrepareUserOperationRule;
import com.coinbase.cdp.openapi.model.SendEndUserEvmTransactionRule;
import com.coinbase.cdp.openapi.model.SendEndUserSolTransactionRule;
import com.coinbase.cdp.openapi.model.SendEvmTransactionRule;
import com.coinbase.cdp.openapi.model.SendSolTransactionRule;
import com.coinbase.cdp.openapi.model.SendUserOperationRule;
import com.coinbase.cdp.openapi.model.SignEndUserEvmHashRule;
import com.coinbase.cdp.openapi.model.SignEndUserEvmMessageRule;
import com.coinbase.cdp.openapi.model.SignEndUserEvmTransactionRule;
import com.coinbase.cdp.openapi.model.SignEndUserEvmTypedDataRule;
import com.coinbase.cdp.openapi.model.SignEndUserSolMessageCriteria;
import com.coinbase.cdp.openapi.model.SignEndUserSolMessageRule;
import com.coinbase.cdp.openapi.model.SignEndUserSolTransactionRule;
import com.coinbase.cdp.openapi.model.SignEvmHashRule;
import com.coinbase.cdp.openapi.model.SignEvmMessageRule;
import com.coinbase.cdp.openapi.model.SignEvmTransactionRule;
import com.coinbase.cdp.openapi.model.SignEvmTypedDataRule;
import com.coinbase.cdp.openapi.model.SignSolMessageRule;
import com.coinbase.cdp.openapi.model.SignSolTransactionRule;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.coinbase.cdp.openapi.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = Rule.RuleDeserializer.class)
@JsonSerialize(using = Rule.RuleSerializer.class)
public class Rule extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Rule.class.getName());

    public static class RuleSerializer extends StdSerializer<Rule> {
        public RuleSerializer(Class<Rule> t) {
            super(t);
        }

        public RuleSerializer() {
            this(null);
        }

        @Override
        public void serialize(Rule value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class RuleDeserializer extends StdDeserializer<Rule> {
        public RuleDeserializer() {
            this(Rule.class);
        }

        public RuleDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public Rule deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize PrepareUserOperationRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PrepareUserOperationRule.class.equals(Integer.class) || PrepareUserOperationRule.class.equals(Long.class) || PrepareUserOperationRule.class.equals(Float.class) || PrepareUserOperationRule.class.equals(Double.class) || PrepareUserOperationRule.class.equals(Boolean.class) || PrepareUserOperationRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PrepareUserOperationRule.class.equals(Integer.class) || PrepareUserOperationRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PrepareUserOperationRule.class.equals(Float.class) || PrepareUserOperationRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PrepareUserOperationRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PrepareUserOperationRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PrepareUserOperationRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PrepareUserOperationRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PrepareUserOperationRule'", e);
            }

            // deserialize SendEndUserEvmTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SendEndUserEvmTransactionRule.class.equals(Integer.class) || SendEndUserEvmTransactionRule.class.equals(Long.class) || SendEndUserEvmTransactionRule.class.equals(Float.class) || SendEndUserEvmTransactionRule.class.equals(Double.class) || SendEndUserEvmTransactionRule.class.equals(Boolean.class) || SendEndUserEvmTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SendEndUserEvmTransactionRule.class.equals(Integer.class) || SendEndUserEvmTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SendEndUserEvmTransactionRule.class.equals(Float.class) || SendEndUserEvmTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SendEndUserEvmTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SendEndUserEvmTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SendEndUserEvmTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SendEndUserEvmTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SendEndUserEvmTransactionRule'", e);
            }

            // deserialize SendEndUserSolTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SendEndUserSolTransactionRule.class.equals(Integer.class) || SendEndUserSolTransactionRule.class.equals(Long.class) || SendEndUserSolTransactionRule.class.equals(Float.class) || SendEndUserSolTransactionRule.class.equals(Double.class) || SendEndUserSolTransactionRule.class.equals(Boolean.class) || SendEndUserSolTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SendEndUserSolTransactionRule.class.equals(Integer.class) || SendEndUserSolTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SendEndUserSolTransactionRule.class.equals(Float.class) || SendEndUserSolTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SendEndUserSolTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SendEndUserSolTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SendEndUserSolTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SendEndUserSolTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SendEndUserSolTransactionRule'", e);
            }

            // deserialize SendEvmTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SendEvmTransactionRule.class.equals(Integer.class) || SendEvmTransactionRule.class.equals(Long.class) || SendEvmTransactionRule.class.equals(Float.class) || SendEvmTransactionRule.class.equals(Double.class) || SendEvmTransactionRule.class.equals(Boolean.class) || SendEvmTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SendEvmTransactionRule.class.equals(Integer.class) || SendEvmTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SendEvmTransactionRule.class.equals(Float.class) || SendEvmTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SendEvmTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SendEvmTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SendEvmTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SendEvmTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SendEvmTransactionRule'", e);
            }

            // deserialize SendSolTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SendSolTransactionRule.class.equals(Integer.class) || SendSolTransactionRule.class.equals(Long.class) || SendSolTransactionRule.class.equals(Float.class) || SendSolTransactionRule.class.equals(Double.class) || SendSolTransactionRule.class.equals(Boolean.class) || SendSolTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SendSolTransactionRule.class.equals(Integer.class) || SendSolTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SendSolTransactionRule.class.equals(Float.class) || SendSolTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SendSolTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SendSolTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SendSolTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SendSolTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SendSolTransactionRule'", e);
            }

            // deserialize SendUserOperationRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SendUserOperationRule.class.equals(Integer.class) || SendUserOperationRule.class.equals(Long.class) || SendUserOperationRule.class.equals(Float.class) || SendUserOperationRule.class.equals(Double.class) || SendUserOperationRule.class.equals(Boolean.class) || SendUserOperationRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SendUserOperationRule.class.equals(Integer.class) || SendUserOperationRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SendUserOperationRule.class.equals(Float.class) || SendUserOperationRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SendUserOperationRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SendUserOperationRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SendUserOperationRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SendUserOperationRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SendUserOperationRule'", e);
            }

            // deserialize SignEndUserEvmHashRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserEvmHashRule.class.equals(Integer.class) || SignEndUserEvmHashRule.class.equals(Long.class) || SignEndUserEvmHashRule.class.equals(Float.class) || SignEndUserEvmHashRule.class.equals(Double.class) || SignEndUserEvmHashRule.class.equals(Boolean.class) || SignEndUserEvmHashRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserEvmHashRule.class.equals(Integer.class) || SignEndUserEvmHashRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserEvmHashRule.class.equals(Float.class) || SignEndUserEvmHashRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserEvmHashRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserEvmHashRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserEvmHashRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserEvmHashRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserEvmHashRule'", e);
            }

            // deserialize SignEndUserEvmMessageRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserEvmMessageRule.class.equals(Integer.class) || SignEndUserEvmMessageRule.class.equals(Long.class) || SignEndUserEvmMessageRule.class.equals(Float.class) || SignEndUserEvmMessageRule.class.equals(Double.class) || SignEndUserEvmMessageRule.class.equals(Boolean.class) || SignEndUserEvmMessageRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserEvmMessageRule.class.equals(Integer.class) || SignEndUserEvmMessageRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserEvmMessageRule.class.equals(Float.class) || SignEndUserEvmMessageRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserEvmMessageRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserEvmMessageRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserEvmMessageRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserEvmMessageRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserEvmMessageRule'", e);
            }

            // deserialize SignEndUserEvmTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserEvmTransactionRule.class.equals(Integer.class) || SignEndUserEvmTransactionRule.class.equals(Long.class) || SignEndUserEvmTransactionRule.class.equals(Float.class) || SignEndUserEvmTransactionRule.class.equals(Double.class) || SignEndUserEvmTransactionRule.class.equals(Boolean.class) || SignEndUserEvmTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserEvmTransactionRule.class.equals(Integer.class) || SignEndUserEvmTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserEvmTransactionRule.class.equals(Float.class) || SignEndUserEvmTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserEvmTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserEvmTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserEvmTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserEvmTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserEvmTransactionRule'", e);
            }

            // deserialize SignEndUserEvmTypedDataRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserEvmTypedDataRule.class.equals(Integer.class) || SignEndUserEvmTypedDataRule.class.equals(Long.class) || SignEndUserEvmTypedDataRule.class.equals(Float.class) || SignEndUserEvmTypedDataRule.class.equals(Double.class) || SignEndUserEvmTypedDataRule.class.equals(Boolean.class) || SignEndUserEvmTypedDataRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserEvmTypedDataRule.class.equals(Integer.class) || SignEndUserEvmTypedDataRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserEvmTypedDataRule.class.equals(Float.class) || SignEndUserEvmTypedDataRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserEvmTypedDataRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserEvmTypedDataRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserEvmTypedDataRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserEvmTypedDataRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserEvmTypedDataRule'", e);
            }

            // deserialize SignEndUserSolMessageRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserSolMessageRule.class.equals(Integer.class) || SignEndUserSolMessageRule.class.equals(Long.class) || SignEndUserSolMessageRule.class.equals(Float.class) || SignEndUserSolMessageRule.class.equals(Double.class) || SignEndUserSolMessageRule.class.equals(Boolean.class) || SignEndUserSolMessageRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserSolMessageRule.class.equals(Integer.class) || SignEndUserSolMessageRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserSolMessageRule.class.equals(Float.class) || SignEndUserSolMessageRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserSolMessageRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserSolMessageRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserSolMessageRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserSolMessageRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserSolMessageRule'", e);
            }

            // deserialize SignEndUserSolTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEndUserSolTransactionRule.class.equals(Integer.class) || SignEndUserSolTransactionRule.class.equals(Long.class) || SignEndUserSolTransactionRule.class.equals(Float.class) || SignEndUserSolTransactionRule.class.equals(Double.class) || SignEndUserSolTransactionRule.class.equals(Boolean.class) || SignEndUserSolTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEndUserSolTransactionRule.class.equals(Integer.class) || SignEndUserSolTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEndUserSolTransactionRule.class.equals(Float.class) || SignEndUserSolTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEndUserSolTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEndUserSolTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEndUserSolTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEndUserSolTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEndUserSolTransactionRule'", e);
            }

            // deserialize SignEvmHashRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEvmHashRule.class.equals(Integer.class) || SignEvmHashRule.class.equals(Long.class) || SignEvmHashRule.class.equals(Float.class) || SignEvmHashRule.class.equals(Double.class) || SignEvmHashRule.class.equals(Boolean.class) || SignEvmHashRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEvmHashRule.class.equals(Integer.class) || SignEvmHashRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEvmHashRule.class.equals(Float.class) || SignEvmHashRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEvmHashRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEvmHashRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEvmHashRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEvmHashRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEvmHashRule'", e);
            }

            // deserialize SignEvmMessageRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEvmMessageRule.class.equals(Integer.class) || SignEvmMessageRule.class.equals(Long.class) || SignEvmMessageRule.class.equals(Float.class) || SignEvmMessageRule.class.equals(Double.class) || SignEvmMessageRule.class.equals(Boolean.class) || SignEvmMessageRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEvmMessageRule.class.equals(Integer.class) || SignEvmMessageRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEvmMessageRule.class.equals(Float.class) || SignEvmMessageRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEvmMessageRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEvmMessageRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEvmMessageRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEvmMessageRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEvmMessageRule'", e);
            }

            // deserialize SignEvmTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEvmTransactionRule.class.equals(Integer.class) || SignEvmTransactionRule.class.equals(Long.class) || SignEvmTransactionRule.class.equals(Float.class) || SignEvmTransactionRule.class.equals(Double.class) || SignEvmTransactionRule.class.equals(Boolean.class) || SignEvmTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEvmTransactionRule.class.equals(Integer.class) || SignEvmTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEvmTransactionRule.class.equals(Float.class) || SignEvmTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEvmTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEvmTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEvmTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEvmTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEvmTransactionRule'", e);
            }

            // deserialize SignEvmTypedDataRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignEvmTypedDataRule.class.equals(Integer.class) || SignEvmTypedDataRule.class.equals(Long.class) || SignEvmTypedDataRule.class.equals(Float.class) || SignEvmTypedDataRule.class.equals(Double.class) || SignEvmTypedDataRule.class.equals(Boolean.class) || SignEvmTypedDataRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignEvmTypedDataRule.class.equals(Integer.class) || SignEvmTypedDataRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignEvmTypedDataRule.class.equals(Float.class) || SignEvmTypedDataRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignEvmTypedDataRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignEvmTypedDataRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignEvmTypedDataRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignEvmTypedDataRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignEvmTypedDataRule'", e);
            }

            // deserialize SignSolMessageRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignSolMessageRule.class.equals(Integer.class) || SignSolMessageRule.class.equals(Long.class) || SignSolMessageRule.class.equals(Float.class) || SignSolMessageRule.class.equals(Double.class) || SignSolMessageRule.class.equals(Boolean.class) || SignSolMessageRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignSolMessageRule.class.equals(Integer.class) || SignSolMessageRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignSolMessageRule.class.equals(Float.class) || SignSolMessageRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignSolMessageRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignSolMessageRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignSolMessageRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignSolMessageRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignSolMessageRule'", e);
            }

            // deserialize SignSolTransactionRule
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SignSolTransactionRule.class.equals(Integer.class) || SignSolTransactionRule.class.equals(Long.class) || SignSolTransactionRule.class.equals(Float.class) || SignSolTransactionRule.class.equals(Double.class) || SignSolTransactionRule.class.equals(Boolean.class) || SignSolTransactionRule.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SignSolTransactionRule.class.equals(Integer.class) || SignSolTransactionRule.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SignSolTransactionRule.class.equals(Float.class) || SignSolTransactionRule.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SignSolTransactionRule.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SignSolTransactionRule.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SignSolTransactionRule.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SignSolTransactionRule'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SignSolTransactionRule'", e);
            }

            if (match == 1) {
                Rule ret = new Rule();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for Rule: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public Rule getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "Rule cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public Rule() {
        super("oneOf", Boolean.FALSE);
    }

    public Rule(PrepareUserOperationRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SendEndUserEvmTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SendEndUserSolTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SendEvmTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SendSolTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SendUserOperationRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserEvmHashRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserEvmMessageRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserEvmTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserEvmTypedDataRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserSolMessageRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEndUserSolTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEvmHashRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEvmMessageRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEvmTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignEvmTypedDataRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignSolMessageRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Rule(SignSolTransactionRule o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("PrepareUserOperationRule", PrepareUserOperationRule.class);
        schemas.put("SendEndUserEvmTransactionRule", SendEndUserEvmTransactionRule.class);
        schemas.put("SendEndUserSolTransactionRule", SendEndUserSolTransactionRule.class);
        schemas.put("SendEvmTransactionRule", SendEvmTransactionRule.class);
        schemas.put("SendSolTransactionRule", SendSolTransactionRule.class);
        schemas.put("SendUserOperationRule", SendUserOperationRule.class);
        schemas.put("SignEndUserEvmHashRule", SignEndUserEvmHashRule.class);
        schemas.put("SignEndUserEvmMessageRule", SignEndUserEvmMessageRule.class);
        schemas.put("SignEndUserEvmTransactionRule", SignEndUserEvmTransactionRule.class);
        schemas.put("SignEndUserEvmTypedDataRule", SignEndUserEvmTypedDataRule.class);
        schemas.put("SignEndUserSolMessageRule", SignEndUserSolMessageRule.class);
        schemas.put("SignEndUserSolTransactionRule", SignEndUserSolTransactionRule.class);
        schemas.put("SignEvmHashRule", SignEvmHashRule.class);
        schemas.put("SignEvmMessageRule", SignEvmMessageRule.class);
        schemas.put("SignEvmTransactionRule", SignEvmTransactionRule.class);
        schemas.put("SignEvmTypedDataRule", SignEvmTypedDataRule.class);
        schemas.put("SignSolMessageRule", SignSolMessageRule.class);
        schemas.put("SignSolTransactionRule", SignSolTransactionRule.class);
        JSON.registerDescendants(Rule.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return Rule.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PrepareUserOperationRule, SendEndUserEvmTransactionRule, SendEndUserSolTransactionRule, SendEvmTransactionRule, SendSolTransactionRule, SendUserOperationRule, SignEndUserEvmHashRule, SignEndUserEvmMessageRule, SignEndUserEvmTransactionRule, SignEndUserEvmTypedDataRule, SignEndUserSolMessageRule, SignEndUserSolTransactionRule, SignEvmHashRule, SignEvmMessageRule, SignEvmTransactionRule, SignEvmTypedDataRule, SignSolMessageRule, SignSolTransactionRule
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(PrepareUserOperationRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SendEndUserEvmTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SendEndUserSolTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SendEvmTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SendSolTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SendUserOperationRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserEvmHashRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserEvmMessageRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserEvmTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserEvmTypedDataRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserSolMessageRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEndUserSolTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEvmHashRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEvmMessageRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEvmTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignEvmTypedDataRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignSolMessageRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SignSolTransactionRule.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PrepareUserOperationRule, SendEndUserEvmTransactionRule, SendEndUserSolTransactionRule, SendEvmTransactionRule, SendSolTransactionRule, SendUserOperationRule, SignEndUserEvmHashRule, SignEndUserEvmMessageRule, SignEndUserEvmTransactionRule, SignEndUserEvmTypedDataRule, SignEndUserSolMessageRule, SignEndUserSolTransactionRule, SignEvmHashRule, SignEvmMessageRule, SignEvmTransactionRule, SignEvmTypedDataRule, SignSolMessageRule, SignSolTransactionRule");
    }

    /**
     * Get the actual instance, which can be the following:
     * PrepareUserOperationRule, SendEndUserEvmTransactionRule, SendEndUserSolTransactionRule, SendEvmTransactionRule, SendSolTransactionRule, SendUserOperationRule, SignEndUserEvmHashRule, SignEndUserEvmMessageRule, SignEndUserEvmTransactionRule, SignEndUserEvmTypedDataRule, SignEndUserSolMessageRule, SignEndUserSolTransactionRule, SignEvmHashRule, SignEvmMessageRule, SignEvmTransactionRule, SignEvmTypedDataRule, SignSolMessageRule, SignSolTransactionRule
     *
     * @return The actual instance (PrepareUserOperationRule, SendEndUserEvmTransactionRule, SendEndUserSolTransactionRule, SendEvmTransactionRule, SendSolTransactionRule, SendUserOperationRule, SignEndUserEvmHashRule, SignEndUserEvmMessageRule, SignEndUserEvmTransactionRule, SignEndUserEvmTypedDataRule, SignEndUserSolMessageRule, SignEndUserSolTransactionRule, SignEvmHashRule, SignEvmMessageRule, SignEvmTransactionRule, SignEvmTypedDataRule, SignSolMessageRule, SignSolTransactionRule)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PrepareUserOperationRule`. If the actual instance is not `PrepareUserOperationRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PrepareUserOperationRule`
     * @throws ClassCastException if the instance is not `PrepareUserOperationRule`
     */
    public PrepareUserOperationRule getPrepareUserOperationRule() throws ClassCastException {
        return (PrepareUserOperationRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SendEndUserEvmTransactionRule`. If the actual instance is not `SendEndUserEvmTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SendEndUserEvmTransactionRule`
     * @throws ClassCastException if the instance is not `SendEndUserEvmTransactionRule`
     */
    public SendEndUserEvmTransactionRule getSendEndUserEvmTransactionRule() throws ClassCastException {
        return (SendEndUserEvmTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SendEndUserSolTransactionRule`. If the actual instance is not `SendEndUserSolTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SendEndUserSolTransactionRule`
     * @throws ClassCastException if the instance is not `SendEndUserSolTransactionRule`
     */
    public SendEndUserSolTransactionRule getSendEndUserSolTransactionRule() throws ClassCastException {
        return (SendEndUserSolTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SendEvmTransactionRule`. If the actual instance is not `SendEvmTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SendEvmTransactionRule`
     * @throws ClassCastException if the instance is not `SendEvmTransactionRule`
     */
    public SendEvmTransactionRule getSendEvmTransactionRule() throws ClassCastException {
        return (SendEvmTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SendSolTransactionRule`. If the actual instance is not `SendSolTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SendSolTransactionRule`
     * @throws ClassCastException if the instance is not `SendSolTransactionRule`
     */
    public SendSolTransactionRule getSendSolTransactionRule() throws ClassCastException {
        return (SendSolTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SendUserOperationRule`. If the actual instance is not `SendUserOperationRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SendUserOperationRule`
     * @throws ClassCastException if the instance is not `SendUserOperationRule`
     */
    public SendUserOperationRule getSendUserOperationRule() throws ClassCastException {
        return (SendUserOperationRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserEvmHashRule`. If the actual instance is not `SignEndUserEvmHashRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserEvmHashRule`
     * @throws ClassCastException if the instance is not `SignEndUserEvmHashRule`
     */
    public SignEndUserEvmHashRule getSignEndUserEvmHashRule() throws ClassCastException {
        return (SignEndUserEvmHashRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserEvmMessageRule`. If the actual instance is not `SignEndUserEvmMessageRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserEvmMessageRule`
     * @throws ClassCastException if the instance is not `SignEndUserEvmMessageRule`
     */
    public SignEndUserEvmMessageRule getSignEndUserEvmMessageRule() throws ClassCastException {
        return (SignEndUserEvmMessageRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserEvmTransactionRule`. If the actual instance is not `SignEndUserEvmTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserEvmTransactionRule`
     * @throws ClassCastException if the instance is not `SignEndUserEvmTransactionRule`
     */
    public SignEndUserEvmTransactionRule getSignEndUserEvmTransactionRule() throws ClassCastException {
        return (SignEndUserEvmTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserEvmTypedDataRule`. If the actual instance is not `SignEndUserEvmTypedDataRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserEvmTypedDataRule`
     * @throws ClassCastException if the instance is not `SignEndUserEvmTypedDataRule`
     */
    public SignEndUserEvmTypedDataRule getSignEndUserEvmTypedDataRule() throws ClassCastException {
        return (SignEndUserEvmTypedDataRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserSolMessageRule`. If the actual instance is not `SignEndUserSolMessageRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserSolMessageRule`
     * @throws ClassCastException if the instance is not `SignEndUserSolMessageRule`
     */
    public SignEndUserSolMessageRule getSignEndUserSolMessageRule() throws ClassCastException {
        return (SignEndUserSolMessageRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEndUserSolTransactionRule`. If the actual instance is not `SignEndUserSolTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEndUserSolTransactionRule`
     * @throws ClassCastException if the instance is not `SignEndUserSolTransactionRule`
     */
    public SignEndUserSolTransactionRule getSignEndUserSolTransactionRule() throws ClassCastException {
        return (SignEndUserSolTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEvmHashRule`. If the actual instance is not `SignEvmHashRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEvmHashRule`
     * @throws ClassCastException if the instance is not `SignEvmHashRule`
     */
    public SignEvmHashRule getSignEvmHashRule() throws ClassCastException {
        return (SignEvmHashRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEvmMessageRule`. If the actual instance is not `SignEvmMessageRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEvmMessageRule`
     * @throws ClassCastException if the instance is not `SignEvmMessageRule`
     */
    public SignEvmMessageRule getSignEvmMessageRule() throws ClassCastException {
        return (SignEvmMessageRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEvmTransactionRule`. If the actual instance is not `SignEvmTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEvmTransactionRule`
     * @throws ClassCastException if the instance is not `SignEvmTransactionRule`
     */
    public SignEvmTransactionRule getSignEvmTransactionRule() throws ClassCastException {
        return (SignEvmTransactionRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignEvmTypedDataRule`. If the actual instance is not `SignEvmTypedDataRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignEvmTypedDataRule`
     * @throws ClassCastException if the instance is not `SignEvmTypedDataRule`
     */
    public SignEvmTypedDataRule getSignEvmTypedDataRule() throws ClassCastException {
        return (SignEvmTypedDataRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignSolMessageRule`. If the actual instance is not `SignSolMessageRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignSolMessageRule`
     * @throws ClassCastException if the instance is not `SignSolMessageRule`
     */
    public SignSolMessageRule getSignSolMessageRule() throws ClassCastException {
        return (SignSolMessageRule)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SignSolTransactionRule`. If the actual instance is not `SignSolTransactionRule`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SignSolTransactionRule`
     * @throws ClassCastException if the instance is not `SignSolTransactionRule`
     */
    public SignSolTransactionRule getSignSolTransactionRule() throws ClassCastException {
        return (SignSolTransactionRule)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof SignEvmTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEvmTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SendEvmTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SendEvmTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEvmMessageRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEvmMessageRule)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEvmTypedDataRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEvmTypedDataRule)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignSolTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignSolTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SendSolTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SendSolTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignSolMessageRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignSolMessageRule)getActualInstance()).toUrlQueryString(prefix + "one_of_6" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEvmHashRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEvmHashRule)getActualInstance()).toUrlQueryString(prefix + "one_of_7" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PrepareUserOperationRule) {
        if (getActualInstance() != null) {
          joiner.add(((PrepareUserOperationRule)getActualInstance()).toUrlQueryString(prefix + "one_of_8" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SendUserOperationRule) {
        if (getActualInstance() != null) {
          joiner.add(((SendUserOperationRule)getActualInstance()).toUrlQueryString(prefix + "one_of_9" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserEvmTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserEvmTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_10" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SendEndUserEvmTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SendEndUserEvmTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_11" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserEvmMessageRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserEvmMessageRule)getActualInstance()).toUrlQueryString(prefix + "one_of_12" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserEvmTypedDataRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserEvmTypedDataRule)getActualInstance()).toUrlQueryString(prefix + "one_of_13" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserEvmHashRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserEvmHashRule)getActualInstance()).toUrlQueryString(prefix + "one_of_14" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserSolTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserSolTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_15" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SendEndUserSolTransactionRule) {
        if (getActualInstance() != null) {
          joiner.add(((SendEndUserSolTransactionRule)getActualInstance()).toUrlQueryString(prefix + "one_of_16" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SignEndUserSolMessageRule) {
        if (getActualInstance() != null) {
          joiner.add(((SignEndUserSolMessageRule)getActualInstance()).toUrlQueryString(prefix + "one_of_17" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

