/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * SendUserOperationRequest
 */
@JsonPropertyOrder({
  SendUserOperationRequest.JSON_PROPERTY_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SendUserOperationRequest {
  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @jakarta.annotation.Nonnull
  private String signature;

  public SendUserOperationRequest() { 
  }

  public SendUserOperationRequest signature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
    return this;
  }

  /**
   * The hex-encoded signature of the user operation. This should be a 65-byte signature consisting of the &#x60;r&#x60;, &#x60;s&#x60;, and &#x60;v&#x60; values of the ECDSA signature. Note that the &#x60;v&#x60; value should conform to the &#x60;personal_sign&#x60; standard, which means it should be 27 or 28.
   * @return signature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignature(@jakarta.annotation.Nonnull String signature) {
    this.signature = signature;
  }


  /**
   * Return true if this sendUserOperation_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendUserOperationRequest sendUserOperationRequest = (SendUserOperationRequest) o;
    return Objects.equals(this.signature, sendUserOperationRequest.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendUserOperationRequest {\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `signature` to the URL query string
    if (getSignature() != null) {
      joiner.add(String.format("%ssignature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SendUserOperationRequest instance;

    public Builder() {
      this(new SendUserOperationRequest());
    }

    protected Builder(SendUserOperationRequest instance) {
      this.instance = instance;
    }

    public SendUserOperationRequest.Builder signature(String signature) {
      this.instance.signature = signature;
      return this;
    }


    /**
    * returns a built SendUserOperationRequest instance.
    *
    * The builder is not reusable.
    */
    public SendUserOperationRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SendUserOperationRequest.Builder builder() {
    return new SendUserOperationRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SendUserOperationRequest.Builder toBuilder() {
    return new SendUserOperationRequest.Builder()
      .signature(getSignature());
  }

}

