/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * SendSolanaTransaction200Response
 */
@JsonPropertyOrder({
  SendSolanaTransaction200Response.JSON_PROPERTY_TRANSACTION_SIGNATURE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SendSolanaTransaction200Response {
  public static final String JSON_PROPERTY_TRANSACTION_SIGNATURE = "transactionSignature";
  @jakarta.annotation.Nonnull
  private String transactionSignature;

  public SendSolanaTransaction200Response() { 
  }

  public SendSolanaTransaction200Response transactionSignature(@jakarta.annotation.Nonnull String transactionSignature) {
    this.transactionSignature = transactionSignature;
    return this;
  }

  /**
   * The base58 encoded transaction signature.
   * @return transactionSignature
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionSignature() {
    return transactionSignature;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionSignature(@jakarta.annotation.Nonnull String transactionSignature) {
    this.transactionSignature = transactionSignature;
  }


  /**
   * Return true if this sendSolanaTransaction_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendSolanaTransaction200Response sendSolanaTransaction200Response = (SendSolanaTransaction200Response) o;
    return Objects.equals(this.transactionSignature, sendSolanaTransaction200Response.transactionSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendSolanaTransaction200Response {\n");
    sb.append("    transactionSignature: ").append(toIndentedString(transactionSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactionSignature` to the URL query string
    if (getTransactionSignature() != null) {
      joiner.add(String.format("%stransactionSignature%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransactionSignature()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SendSolanaTransaction200Response instance;

    public Builder() {
      this(new SendSolanaTransaction200Response());
    }

    protected Builder(SendSolanaTransaction200Response instance) {
      this.instance = instance;
    }

    public SendSolanaTransaction200Response.Builder transactionSignature(String transactionSignature) {
      this.instance.transactionSignature = transactionSignature;
      return this;
    }


    /**
    * returns a built SendSolanaTransaction200Response instance.
    *
    * The builder is not reusable.
    */
    public SendSolanaTransaction200Response build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SendSolanaTransaction200Response.Builder builder() {
    return new SendSolanaTransaction200Response.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SendSolanaTransaction200Response.Builder toBuilder() {
    return new SendSolanaTransaction200Response.Builder()
      .transactionSignature(getTransactionSignature());
  }

}

