/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.EvmDataCondition;
import com.coinbase.cdp.openapi.model.EvmDataCriterion;
import com.coinbase.cdp.openapi.model.EvmDataCriterionAbi;
import com.coinbase.cdp.openapi.model.EvmNetworkCriterion;
import com.coinbase.cdp.openapi.model.NetUSDChangeCriterion;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.coinbase.cdp.openapi.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = SendEndUserEvmAssetCriteriaInner.SendEndUserEvmAssetCriteriaInnerDeserializer.class)
@JsonSerialize(using = SendEndUserEvmAssetCriteriaInner.SendEndUserEvmAssetCriteriaInnerSerializer.class)
public class SendEndUserEvmAssetCriteriaInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SendEndUserEvmAssetCriteriaInner.class.getName());

    public static class SendEndUserEvmAssetCriteriaInnerSerializer extends StdSerializer<SendEndUserEvmAssetCriteriaInner> {
        public SendEndUserEvmAssetCriteriaInnerSerializer(Class<SendEndUserEvmAssetCriteriaInner> t) {
            super(t);
        }

        public SendEndUserEvmAssetCriteriaInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(SendEndUserEvmAssetCriteriaInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SendEndUserEvmAssetCriteriaInnerDeserializer extends StdDeserializer<SendEndUserEvmAssetCriteriaInner> {
        public SendEndUserEvmAssetCriteriaInnerDeserializer() {
            this(SendEndUserEvmAssetCriteriaInner.class);
        }

        public SendEndUserEvmAssetCriteriaInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SendEndUserEvmAssetCriteriaInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize EvmDataCriterion
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (EvmDataCriterion.class.equals(Integer.class) || EvmDataCriterion.class.equals(Long.class) || EvmDataCriterion.class.equals(Float.class) || EvmDataCriterion.class.equals(Double.class) || EvmDataCriterion.class.equals(Boolean.class) || EvmDataCriterion.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((EvmDataCriterion.class.equals(Integer.class) || EvmDataCriterion.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((EvmDataCriterion.class.equals(Float.class) || EvmDataCriterion.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (EvmDataCriterion.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (EvmDataCriterion.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(EvmDataCriterion.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'EvmDataCriterion'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'EvmDataCriterion'", e);
            }

            // deserialize EvmNetworkCriterion
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (EvmNetworkCriterion.class.equals(Integer.class) || EvmNetworkCriterion.class.equals(Long.class) || EvmNetworkCriterion.class.equals(Float.class) || EvmNetworkCriterion.class.equals(Double.class) || EvmNetworkCriterion.class.equals(Boolean.class) || EvmNetworkCriterion.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((EvmNetworkCriterion.class.equals(Integer.class) || EvmNetworkCriterion.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((EvmNetworkCriterion.class.equals(Float.class) || EvmNetworkCriterion.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (EvmNetworkCriterion.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (EvmNetworkCriterion.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(EvmNetworkCriterion.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'EvmNetworkCriterion'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'EvmNetworkCriterion'", e);
            }

            // deserialize NetUSDChangeCriterion
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (NetUSDChangeCriterion.class.equals(Integer.class) || NetUSDChangeCriterion.class.equals(Long.class) || NetUSDChangeCriterion.class.equals(Float.class) || NetUSDChangeCriterion.class.equals(Double.class) || NetUSDChangeCriterion.class.equals(Boolean.class) || NetUSDChangeCriterion.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((NetUSDChangeCriterion.class.equals(Integer.class) || NetUSDChangeCriterion.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((NetUSDChangeCriterion.class.equals(Float.class) || NetUSDChangeCriterion.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (NetUSDChangeCriterion.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (NetUSDChangeCriterion.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(NetUSDChangeCriterion.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'NetUSDChangeCriterion'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'NetUSDChangeCriterion'", e);
            }

            if (match == 1) {
                SendEndUserEvmAssetCriteriaInner ret = new SendEndUserEvmAssetCriteriaInner();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SendEndUserEvmAssetCriteriaInner: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SendEndUserEvmAssetCriteriaInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SendEndUserEvmAssetCriteriaInner cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SendEndUserEvmAssetCriteriaInner() {
        super("oneOf", Boolean.FALSE);
    }

    public SendEndUserEvmAssetCriteriaInner(EvmDataCriterion o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SendEndUserEvmAssetCriteriaInner(EvmNetworkCriterion o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SendEndUserEvmAssetCriteriaInner(NetUSDChangeCriterion o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("EvmDataCriterion", EvmDataCriterion.class);
        schemas.put("EvmNetworkCriterion", EvmNetworkCriterion.class);
        schemas.put("NetUSDChangeCriterion", NetUSDChangeCriterion.class);
        JSON.registerDescendants(SendEndUserEvmAssetCriteriaInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SendEndUserEvmAssetCriteriaInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * EvmDataCriterion, EvmNetworkCriterion, NetUSDChangeCriterion
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(EvmDataCriterion.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(EvmNetworkCriterion.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(NetUSDChangeCriterion.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be EvmDataCriterion, EvmNetworkCriterion, NetUSDChangeCriterion");
    }

    /**
     * Get the actual instance, which can be the following:
     * EvmDataCriterion, EvmNetworkCriterion, NetUSDChangeCriterion
     *
     * @return The actual instance (EvmDataCriterion, EvmNetworkCriterion, NetUSDChangeCriterion)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `EvmDataCriterion`. If the actual instance is not `EvmDataCriterion`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `EvmDataCriterion`
     * @throws ClassCastException if the instance is not `EvmDataCriterion`
     */
    public EvmDataCriterion getEvmDataCriterion() throws ClassCastException {
        return (EvmDataCriterion)super.getActualInstance();
    }

    /**
     * Get the actual instance of `EvmNetworkCriterion`. If the actual instance is not `EvmNetworkCriterion`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `EvmNetworkCriterion`
     * @throws ClassCastException if the instance is not `EvmNetworkCriterion`
     */
    public EvmNetworkCriterion getEvmNetworkCriterion() throws ClassCastException {
        return (EvmNetworkCriterion)super.getActualInstance();
    }

    /**
     * Get the actual instance of `NetUSDChangeCriterion`. If the actual instance is not `NetUSDChangeCriterion`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `NetUSDChangeCriterion`
     * @throws ClassCastException if the instance is not `NetUSDChangeCriterion`
     */
    public NetUSDChangeCriterion getNetUSDChangeCriterion() throws ClassCastException {
        return (NetUSDChangeCriterion)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof EvmNetworkCriterion) {
        if (getActualInstance() != null) {
          joiner.add(((EvmNetworkCriterion)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof EvmDataCriterion) {
        if (getActualInstance() != null) {
          joiner.add(((EvmDataCriterion)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof NetUSDChangeCriterion) {
        if (getActualInstance() != null) {
          joiner.add(((NetUSDChangeCriterion)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

