/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.EIP712Message;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * SignEvmTypedDataWithEndUserAccountRequest
 */
@JsonPropertyOrder({
  SignEvmTypedDataWithEndUserAccountRequest.JSON_PROPERTY_ADDRESS,
  SignEvmTypedDataWithEndUserAccountRequest.JSON_PROPERTY_TYPED_DATA,
  SignEvmTypedDataWithEndUserAccountRequest.JSON_PROPERTY_WALLET_SECRET_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SignEvmTypedDataWithEndUserAccountRequest {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  @jakarta.annotation.Nonnull
  private String address;

  public static final String JSON_PROPERTY_TYPED_DATA = "typedData";
  @jakarta.annotation.Nonnull
  private EIP712Message typedData;

  public static final String JSON_PROPERTY_WALLET_SECRET_ID = "walletSecretId";
  @jakarta.annotation.Nullable
  private String walletSecretId;

  public SignEvmTypedDataWithEndUserAccountRequest() { 
  }

  public SignEvmTypedDataWithEndUserAccountRequest address(@jakarta.annotation.Nonnull String address) {
    this.address = address;
    return this;
  }

  /**
   * The 0x-prefixed address of the EVM account belonging to the end user.
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(@jakarta.annotation.Nonnull String address) {
    this.address = address;
  }


  public SignEvmTypedDataWithEndUserAccountRequest typedData(@jakarta.annotation.Nonnull EIP712Message typedData) {
    this.typedData = typedData;
    return this;
  }

  /**
   * Get typedData
   * @return typedData
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPED_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public EIP712Message getTypedData() {
    return typedData;
  }


  @JsonProperty(JSON_PROPERTY_TYPED_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypedData(@jakarta.annotation.Nonnull EIP712Message typedData) {
    this.typedData = typedData;
  }


  public SignEvmTypedDataWithEndUserAccountRequest walletSecretId(@jakarta.annotation.Nullable String walletSecretId) {
    this.walletSecretId = walletSecretId;
    return this;
  }

  /**
   * Required when not using delegated signing. The ID of the Temporary Wallet Secret that was used to sign the X-Wallet-Auth Header.
   * @return walletSecretId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WALLET_SECRET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWalletSecretId() {
    return walletSecretId;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_SECRET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletSecretId(@jakarta.annotation.Nullable String walletSecretId) {
    this.walletSecretId = walletSecretId;
  }


  /**
   * Return true if this signEvmTypedDataWithEndUserAccount_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignEvmTypedDataWithEndUserAccountRequest signEvmTypedDataWithEndUserAccountRequest = (SignEvmTypedDataWithEndUserAccountRequest) o;
    return Objects.equals(this.address, signEvmTypedDataWithEndUserAccountRequest.address) &&
        Objects.equals(this.typedData, signEvmTypedDataWithEndUserAccountRequest.typedData) &&
        Objects.equals(this.walletSecretId, signEvmTypedDataWithEndUserAccountRequest.walletSecretId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, typedData, walletSecretId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignEvmTypedDataWithEndUserAccountRequest {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    typedData: ").append(toIndentedString(typedData)).append("\n");
    sb.append("    walletSecretId: ").append(toIndentedString(walletSecretId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format("%saddress%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAddress()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `typedData` to the URL query string
    if (getTypedData() != null) {
      joiner.add(getTypedData().toUrlQueryString(prefix + "typedData" + suffix));
    }

    // add `walletSecretId` to the URL query string
    if (getWalletSecretId() != null) {
      joiner.add(String.format("%swalletSecretId%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getWalletSecretId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SignEvmTypedDataWithEndUserAccountRequest instance;

    public Builder() {
      this(new SignEvmTypedDataWithEndUserAccountRequest());
    }

    protected Builder(SignEvmTypedDataWithEndUserAccountRequest instance) {
      this.instance = instance;
    }

    public SignEvmTypedDataWithEndUserAccountRequest.Builder address(String address) {
      this.instance.address = address;
      return this;
    }
    public SignEvmTypedDataWithEndUserAccountRequest.Builder typedData(EIP712Message typedData) {
      this.instance.typedData = typedData;
      return this;
    }
    public SignEvmTypedDataWithEndUserAccountRequest.Builder walletSecretId(String walletSecretId) {
      this.instance.walletSecretId = walletSecretId;
      return this;
    }


    /**
    * returns a built SignEvmTypedDataWithEndUserAccountRequest instance.
    *
    * The builder is not reusable.
    */
    public SignEvmTypedDataWithEndUserAccountRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SignEvmTypedDataWithEndUserAccountRequest.Builder builder() {
    return new SignEvmTypedDataWithEndUserAccountRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SignEvmTypedDataWithEndUserAccountRequest.Builder toBuilder() {
    return new SignEvmTypedDataWithEndUserAccountRequest.Builder()
      .address(getAddress())
      .typedData(getTypedData())
      .walletSecretId(getWalletSecretId());
  }

}

