/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.SolMessageCriterion;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.coinbase.cdp.openapi.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = SignSolMessageCriteriaInner.SignSolMessageCriteriaInnerDeserializer.class)
@JsonSerialize(using = SignSolMessageCriteriaInner.SignSolMessageCriteriaInnerSerializer.class)
public class SignSolMessageCriteriaInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SignSolMessageCriteriaInner.class.getName());

    public static class SignSolMessageCriteriaInnerSerializer extends StdSerializer<SignSolMessageCriteriaInner> {
        public SignSolMessageCriteriaInnerSerializer(Class<SignSolMessageCriteriaInner> t) {
            super(t);
        }

        public SignSolMessageCriteriaInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(SignSolMessageCriteriaInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SignSolMessageCriteriaInnerDeserializer extends StdDeserializer<SignSolMessageCriteriaInner> {
        public SignSolMessageCriteriaInnerDeserializer() {
            this(SignSolMessageCriteriaInner.class);
        }

        public SignSolMessageCriteriaInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SignSolMessageCriteriaInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize SolMessageCriterion
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SolMessageCriterion.class.equals(Integer.class) || SolMessageCriterion.class.equals(Long.class) || SolMessageCriterion.class.equals(Float.class) || SolMessageCriterion.class.equals(Double.class) || SolMessageCriterion.class.equals(Boolean.class) || SolMessageCriterion.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SolMessageCriterion.class.equals(Integer.class) || SolMessageCriterion.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SolMessageCriterion.class.equals(Float.class) || SolMessageCriterion.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SolMessageCriterion.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SolMessageCriterion.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SolMessageCriterion.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SolMessageCriterion'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SolMessageCriterion'", e);
            }

            if (match == 1) {
                SignSolMessageCriteriaInner ret = new SignSolMessageCriteriaInner();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SignSolMessageCriteriaInner: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SignSolMessageCriteriaInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SignSolMessageCriteriaInner cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SignSolMessageCriteriaInner() {
        super("oneOf", Boolean.FALSE);
    }

    public SignSolMessageCriteriaInner(SolMessageCriterion o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SolMessageCriterion", SolMessageCriterion.class);
        JSON.registerDescendants(SignSolMessageCriteriaInner.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SignSolMessageCriteriaInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * SolMessageCriterion
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(SolMessageCriterion.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SolMessageCriterion");
    }

    /**
     * Get the actual instance, which can be the following:
     * SolMessageCriterion
     *
     * @return The actual instance (SolMessageCriterion)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SolMessageCriterion`. If the actual instance is not `SolMessageCriterion`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SolMessageCriterion`
     * @throws ClassCastException if the instance is not `SolMessageCriterion`
     */
    public SolMessageCriterion getSolMessageCriterion() throws ClassCastException {
        return (SolMessageCriterion)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof SolMessageCriterion) {
        if (getActualInstance() != null) {
          joiner.add(((SolMessageCriterion)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

