/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * A single parameter condition to apply against a specific instruction&#39;s parameters.
 */
@JsonPropertyOrder({
  SolDataParameterConditionList.JSON_PROPERTY_NAME,
  SolDataParameterConditionList.JSON_PROPERTY_OPERATOR,
  SolDataParameterConditionList.JSON_PROPERTY_VALUES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SolDataParameterConditionList {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  /**
   * The operator to use for the comparison. The value resolved at the &#x60;name&#x60; will be on the left-hand side of the operator, and the &#x60;value&#x60; field will be on the right-hand side.
   */
  public enum OperatorEnum {
    IN(String.valueOf("in")),
    
    NOT_IN(String.valueOf("not in"));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @jakarta.annotation.Nonnull
  private OperatorEnum operator;

  public static final String JSON_PROPERTY_VALUES = "values";
  @jakarta.annotation.Nonnull
  private List<String> values = new ArrayList<>();

  public SolDataParameterConditionList() { 
  }

  public SolDataParameterConditionList name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The parameter name.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public SolDataParameterConditionList operator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * The operator to use for the comparison. The value resolved at the &#x60;name&#x60; will be on the left-hand side of the operator, and the &#x60;value&#x60; field will be on the right-hand side.
   * @return operator
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
  }


  public SolDataParameterConditionList values(@jakarta.annotation.Nonnull List<String> values) {
    this.values = values;
    return this;
  }

  public SolDataParameterConditionList addValuesItem(String valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

  /**
   * The values to compare against.
   * @return values
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setValues(@jakarta.annotation.Nonnull List<String> values) {
    this.values = values;
  }


  /**
   * Return true if this SolDataParameterConditionList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolDataParameterConditionList solDataParameterConditionList = (SolDataParameterConditionList) o;
    return Objects.equals(this.name, solDataParameterConditionList.name) &&
        Objects.equals(this.operator, solDataParameterConditionList.operator) &&
        Objects.equals(this.values, solDataParameterConditionList.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, operator, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolDataParameterConditionList {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format("%soperator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOperator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `values` to the URL query string
    if (getValues() != null) {
      for (int i = 0; i < getValues().size(); i++) {
        joiner.add(String.format("%svalues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getValues().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private SolDataParameterConditionList instance;

    public Builder() {
      this(new SolDataParameterConditionList());
    }

    protected Builder(SolDataParameterConditionList instance) {
      this.instance = instance;
    }

    public SolDataParameterConditionList.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public SolDataParameterConditionList.Builder operator(OperatorEnum operator) {
      this.instance.operator = operator;
      return this;
    }
    public SolDataParameterConditionList.Builder values(List<String> values) {
      this.instance.values = values;
      return this;
    }


    /**
    * returns a built SolDataParameterConditionList instance.
    *
    * The builder is not reusable.
    */
    public SolDataParameterConditionList build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SolDataParameterConditionList.Builder builder() {
    return new SolDataParameterConditionList.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SolDataParameterConditionList.Builder toBuilder() {
    return new SolDataParameterConditionList.Builder()
      .name(getName())
      .operator(getOperator())
      .values(getValues());
  }

}

