/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * The criterion for the SOL value in lamports of a native transfer instruction in a Solana transaction.
 */
@JsonPropertyOrder({
  SolValueCriterion.JSON_PROPERTY_TYPE,
  SolValueCriterion.JSON_PROPERTY_SOL_VALUE,
  SolValueCriterion.JSON_PROPERTY_OPERATOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class SolValueCriterion {
  /**
   * The type of criterion to use. This should be &#x60;solValue&#x60;.
   */
  public enum TypeEnum {
    SOL_VALUE(String.valueOf("solValue"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_SOL_VALUE = "solValue";
  @jakarta.annotation.Nonnull
  private String solValue;

  /**
   * The operator to use for the comparison. The transaction instruction&#39;s &#x60;value&#x60; field will be on the left-hand side of the operator, and the &#x60;solValue&#x60; field will be on the right-hand side.
   */
  public enum OperatorEnum {
    GREATER_THAN(String.valueOf(">")),
    
    GREATER_THAN_OR_EQUAL_TO(String.valueOf(">=")),
    
    LESS_THAN(String.valueOf("<")),
    
    LESS_THAN_OR_EQUAL_TO(String.valueOf("<=")),
    
    DOUBLE_EQUAL(String.valueOf("=="));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @jakarta.annotation.Nonnull
  private OperatorEnum operator;

  public SolValueCriterion() { 
  }

  public SolValueCriterion type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * The type of criterion to use. This should be &#x60;solValue&#x60;.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public SolValueCriterion solValue(@jakarta.annotation.Nonnull String solValue) {
    this.solValue = solValue;
    return this;
  }

  /**
   * The amount of SOL in lamports that the transaction instruction&#39;s &#x60;value&#x60; field should be compared to.
   * @return solValue
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOL_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSolValue() {
    return solValue;
  }


  @JsonProperty(JSON_PROPERTY_SOL_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSolValue(@jakarta.annotation.Nonnull String solValue) {
    this.solValue = solValue;
  }


  public SolValueCriterion operator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * The operator to use for the comparison. The transaction instruction&#39;s &#x60;value&#x60; field will be on the left-hand side of the operator, and the &#x60;solValue&#x60; field will be on the right-hand side.
   * @return operator
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperator(@jakarta.annotation.Nonnull OperatorEnum operator) {
    this.operator = operator;
  }


  /**
   * Return true if this SolValueCriterion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolValueCriterion solValueCriterion = (SolValueCriterion) o;
    return Objects.equals(this.type, solValueCriterion.type) &&
        Objects.equals(this.solValue, solValueCriterion.solValue) &&
        Objects.equals(this.operator, solValueCriterion.operator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, solValue, operator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolValueCriterion {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    solValue: ").append(toIndentedString(solValue)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `solValue` to the URL query string
    if (getSolValue() != null) {
      joiner.add(String.format("%ssolValue%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSolValue()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format("%soperator%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getOperator()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SolValueCriterion instance;

    public Builder() {
      this(new SolValueCriterion());
    }

    protected Builder(SolValueCriterion instance) {
      this.instance = instance;
    }

    public SolValueCriterion.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public SolValueCriterion.Builder solValue(String solValue) {
      this.instance.solValue = solValue;
      return this;
    }
    public SolValueCriterion.Builder operator(OperatorEnum operator) {
      this.instance.operator = operator;
      return this;
    }


    /**
    * returns a built SolValueCriterion instance.
    *
    * The builder is not reusable.
    */
    public SolValueCriterion build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SolValueCriterion.Builder builder() {
    return new SolValueCriterion.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SolValueCriterion.Builder toBuilder() {
    return new SolValueCriterion.Builder()
      .type(getType())
      .solValue(getSolValue())
      .operator(getOperator());
  }

}

