/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.X402PaymentPayload;
import com.coinbase.cdp.openapi.model.X402PaymentRequirements;
import com.coinbase.cdp.openapi.model.X402Version;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * VerifyX402PaymentRequest
 */
@JsonPropertyOrder({
  VerifyX402PaymentRequest.JSON_PROPERTY_X402_VERSION,
  VerifyX402PaymentRequest.JSON_PROPERTY_PAYMENT_PAYLOAD,
  VerifyX402PaymentRequest.JSON_PROPERTY_PAYMENT_REQUIREMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class VerifyX402PaymentRequest {
  public static final String JSON_PROPERTY_X402_VERSION = "x402Version";
  @jakarta.annotation.Nonnull
  private X402Version x402Version;

  public static final String JSON_PROPERTY_PAYMENT_PAYLOAD = "paymentPayload";
  @jakarta.annotation.Nonnull
  private X402PaymentPayload paymentPayload;

  public static final String JSON_PROPERTY_PAYMENT_REQUIREMENTS = "paymentRequirements";
  @jakarta.annotation.Nonnull
  private X402PaymentRequirements paymentRequirements;

  public VerifyX402PaymentRequest() { 
  }

  public VerifyX402PaymentRequest x402Version(@jakarta.annotation.Nonnull X402Version x402Version) {
    this.x402Version = x402Version;
    return this;
  }

  /**
   * Get x402Version
   * @return x402Version
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_X402_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402Version getX402Version() {
    return x402Version;
  }


  @JsonProperty(JSON_PROPERTY_X402_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setX402Version(@jakarta.annotation.Nonnull X402Version x402Version) {
    this.x402Version = x402Version;
  }


  public VerifyX402PaymentRequest paymentPayload(@jakarta.annotation.Nonnull X402PaymentPayload paymentPayload) {
    this.paymentPayload = paymentPayload;
    return this;
  }

  /**
   * Get paymentPayload
   * @return paymentPayload
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402PaymentPayload getPaymentPayload() {
    return paymentPayload;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PAYLOAD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentPayload(@jakarta.annotation.Nonnull X402PaymentPayload paymentPayload) {
    this.paymentPayload = paymentPayload;
  }


  public VerifyX402PaymentRequest paymentRequirements(@jakarta.annotation.Nonnull X402PaymentRequirements paymentRequirements) {
    this.paymentRequirements = paymentRequirements;
    return this;
  }

  /**
   * Get paymentRequirements
   * @return paymentRequirements
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402PaymentRequirements getPaymentRequirements() {
    return paymentRequirements;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUIREMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRequirements(@jakarta.annotation.Nonnull X402PaymentRequirements paymentRequirements) {
    this.paymentRequirements = paymentRequirements;
  }


  /**
   * Return true if this verifyX402Payment_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyX402PaymentRequest verifyX402PaymentRequest = (VerifyX402PaymentRequest) o;
    return Objects.equals(this.x402Version, verifyX402PaymentRequest.x402Version) &&
        Objects.equals(this.paymentPayload, verifyX402PaymentRequest.paymentPayload) &&
        Objects.equals(this.paymentRequirements, verifyX402PaymentRequest.paymentRequirements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x402Version, paymentPayload, paymentRequirements);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyX402PaymentRequest {\n");
    sb.append("    x402Version: ").append(toIndentedString(x402Version)).append("\n");
    sb.append("    paymentPayload: ").append(toIndentedString(paymentPayload)).append("\n");
    sb.append("    paymentRequirements: ").append(toIndentedString(paymentRequirements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `x402Version` to the URL query string
    if (getX402Version() != null) {
      joiner.add(String.format("%sx402Version%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getX402Version()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `paymentPayload` to the URL query string
    if (getPaymentPayload() != null) {
      joiner.add(getPaymentPayload().toUrlQueryString(prefix + "paymentPayload" + suffix));
    }

    // add `paymentRequirements` to the URL query string
    if (getPaymentRequirements() != null) {
      joiner.add(getPaymentRequirements().toUrlQueryString(prefix + "paymentRequirements" + suffix));
    }

    return joiner.toString();
  }

    public static class Builder {

    private VerifyX402PaymentRequest instance;

    public Builder() {
      this(new VerifyX402PaymentRequest());
    }

    protected Builder(VerifyX402PaymentRequest instance) {
      this.instance = instance;
    }

    public VerifyX402PaymentRequest.Builder x402Version(X402Version x402Version) {
      this.instance.x402Version = x402Version;
      return this;
    }
    public VerifyX402PaymentRequest.Builder paymentPayload(X402PaymentPayload paymentPayload) {
      this.instance.paymentPayload = paymentPayload;
      return this;
    }
    public VerifyX402PaymentRequest.Builder paymentRequirements(X402PaymentRequirements paymentRequirements) {
      this.instance.paymentRequirements = paymentRequirements;
      return this;
    }


    /**
    * returns a built VerifyX402PaymentRequest instance.
    *
    * The builder is not reusable.
    */
    public VerifyX402PaymentRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static VerifyX402PaymentRequest.Builder builder() {
    return new VerifyX402PaymentRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public VerifyX402PaymentRequest.Builder toBuilder() {
    return new VerifyX402PaymentRequest.Builder()
      .x402Version(getX402Version())
      .paymentPayload(getPaymentPayload())
      .paymentRequirements(getPaymentRequirements());
  }

}

