/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.WebhookSubscriptionResponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * WebhookSubscriptionListResponse
 */
@JsonPropertyOrder({
  WebhookSubscriptionListResponse.JSON_PROPERTY_NEXT_PAGE_TOKEN,
  WebhookSubscriptionListResponse.JSON_PROPERTY_SUBSCRIPTIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class WebhookSubscriptionListResponse {
  public static final String JSON_PROPERTY_NEXT_PAGE_TOKEN = "nextPageToken";
  @jakarta.annotation.Nullable
  private String nextPageToken;

  public static final String JSON_PROPERTY_SUBSCRIPTIONS = "subscriptions";
  @jakarta.annotation.Nonnull
  private List<WebhookSubscriptionResponse> subscriptions = new ArrayList<>();

  public WebhookSubscriptionListResponse() { 
  }

  public WebhookSubscriptionListResponse nextPageToken(@jakarta.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * The token for the next page of items, if any.
   * @return nextPageToken
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNextPageToken() {
    return nextPageToken;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPageToken(@jakarta.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  public WebhookSubscriptionListResponse subscriptions(@jakarta.annotation.Nonnull List<WebhookSubscriptionResponse> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public WebhookSubscriptionListResponse addSubscriptionsItem(WebhookSubscriptionResponse subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

  /**
   * The list of webhook subscriptions.
   * @return subscriptions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<WebhookSubscriptionResponse> getSubscriptions() {
    return subscriptions;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubscriptions(@jakarta.annotation.Nonnull List<WebhookSubscriptionResponse> subscriptions) {
    this.subscriptions = subscriptions;
  }


  /**
   * Return true if this WebhookSubscriptionListResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookSubscriptionListResponse webhookSubscriptionListResponse = (WebhookSubscriptionListResponse) o;
    return Objects.equals(this.nextPageToken, webhookSubscriptionListResponse.nextPageToken) &&
        Objects.equals(this.subscriptions, webhookSubscriptionListResponse.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextPageToken, subscriptions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookSubscriptionListResponse {\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `nextPageToken` to the URL query string
    if (getNextPageToken() != null) {
      joiner.add(String.format("%snextPageToken%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNextPageToken()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `subscriptions` to the URL query string
    if (getSubscriptions() != null) {
      for (int i = 0; i < getSubscriptions().size(); i++) {
        if (getSubscriptions().get(i) != null) {
          joiner.add(getSubscriptions().get(i).toUrlQueryString(String.format("%ssubscriptions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private WebhookSubscriptionListResponse instance;

    public Builder() {
      this(new WebhookSubscriptionListResponse());
    }

    protected Builder(WebhookSubscriptionListResponse instance) {
      this.instance = instance;
    }

    public WebhookSubscriptionListResponse.Builder nextPageToken(String nextPageToken) {
      this.instance.nextPageToken = nextPageToken;
      return this;
    }
    public WebhookSubscriptionListResponse.Builder subscriptions(List<WebhookSubscriptionResponse> subscriptions) {
      this.instance.subscriptions = subscriptions;
      return this;
    }


    /**
    * returns a built WebhookSubscriptionListResponse instance.
    *
    * The builder is not reusable.
    */
    public WebhookSubscriptionListResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static WebhookSubscriptionListResponse.Builder builder() {
    return new WebhookSubscriptionListResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public WebhookSubscriptionListResponse.Builder toBuilder() {
    return new WebhookSubscriptionListResponse.Builder()
      .nextPageToken(getNextPageToken())
      .subscriptions(getSubscriptions());
  }

}

