/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * The token permissions for the transfer.
 */
@JsonPropertyOrder({
  X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.JSON_PROPERTY_TOKEN,
  X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.JSON_PROPERTY_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted {
  public static final String JSON_PROPERTY_TOKEN = "token";
  @jakarta.annotation.Nonnull
  private String token;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted() { 
  }

  public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted token(@jakarta.annotation.Nonnull String token) {
    this.token = token;
    return this;
  }

  /**
   * The 0x-prefixed, checksum EVM address of the token to transfer.
   * @return token
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getToken() {
    return token;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToken(@jakarta.annotation.Nonnull String token) {
    this.token = token;
  }


  public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted amount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * The amount to transfer in atomic units.
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  /**
   * Return true if this x402ExactEvmPermit2Payload_permit2Authorization_permitted object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted x402ExactEvmPermit2PayloadPermit2AuthorizationPermitted = (X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted) o;
    return Objects.equals(this.token, x402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.token) &&
        Objects.equals(this.amount, x402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted {\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `token` to the URL query string
    if (getToken() != null) {
      joiner.add(String.format("%stoken%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getToken()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format("%samount%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAmount()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted instance;

    public Builder() {
      this(new X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted());
    }

    protected Builder(X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted instance) {
      this.instance = instance;
    }

    public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder token(String token) {
      this.instance.token = token;
      return this;
    }
    public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder amount(String amount) {
      this.instance.amount = amount;
      return this;
    }


    /**
    * returns a built X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted instance.
    *
    * The builder is not reusable.
    */
    public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder builder() {
    return new X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder toBuilder() {
    return new X402ExactEvmPermit2PayloadPermit2AuthorizationPermitted.Builder()
      .token(getToken())
      .amount(getAmount());
  }

}

