/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * The x402 protocol payment requirements that the resource server expects the client&#39;s payment payload to meet.
 */
@JsonPropertyOrder({
  X402V1PaymentRequirements.JSON_PROPERTY_SCHEME,
  X402V1PaymentRequirements.JSON_PROPERTY_NETWORK,
  X402V1PaymentRequirements.JSON_PROPERTY_MAX_AMOUNT_REQUIRED,
  X402V1PaymentRequirements.JSON_PROPERTY_RESOURCE,
  X402V1PaymentRequirements.JSON_PROPERTY_DESCRIPTION,
  X402V1PaymentRequirements.JSON_PROPERTY_MIME_TYPE,
  X402V1PaymentRequirements.JSON_PROPERTY_OUTPUT_SCHEMA,
  X402V1PaymentRequirements.JSON_PROPERTY_PAY_TO,
  X402V1PaymentRequirements.JSON_PROPERTY_MAX_TIMEOUT_SECONDS,
  X402V1PaymentRequirements.JSON_PROPERTY_ASSET,
  X402V1PaymentRequirements.JSON_PROPERTY_EXTRA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class X402V1PaymentRequirements {
  /**
   * The scheme of the payment protocol to use. Currently, the only supported scheme is &#x60;exact&#x60;.
   */
  public enum SchemeEnum {
    EXACT(String.valueOf("exact"));

    private String value;

    SchemeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SchemeEnum fromValue(String value) {
      for (SchemeEnum b : SchemeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SCHEME = "scheme";
  @jakarta.annotation.Nonnull
  private SchemeEnum scheme;

  /**
   * The network of the blockchain to send payment on.
   */
  public enum NetworkEnum {
    BASE_SEPOLIA(String.valueOf("base-sepolia")),
    
    BASE(String.valueOf("base")),
    
    SOLANA_DEVNET(String.valueOf("solana-devnet")),
    
    SOLANA(String.valueOf("solana")),
    
    POLYGON(String.valueOf("polygon"));

    private String value;

    NetworkEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NetworkEnum fromValue(String value) {
      for (NetworkEnum b : NetworkEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_NETWORK = "network";
  @jakarta.annotation.Nonnull
  private NetworkEnum network;

  public static final String JSON_PROPERTY_MAX_AMOUNT_REQUIRED = "maxAmountRequired";
  @jakarta.annotation.Nonnull
  private String maxAmountRequired;

  public static final String JSON_PROPERTY_RESOURCE = "resource";
  @jakarta.annotation.Nonnull
  private String resource;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";
  @jakarta.annotation.Nonnull
  private String mimeType;

  public static final String JSON_PROPERTY_OUTPUT_SCHEMA = "outputSchema";
  @jakarta.annotation.Nullable
  private Map<String, Object> outputSchema = new HashMap<>();

  public static final String JSON_PROPERTY_PAY_TO = "payTo";
  @jakarta.annotation.Nonnull
  private String payTo;

  public static final String JSON_PROPERTY_MAX_TIMEOUT_SECONDS = "maxTimeoutSeconds";
  @jakarta.annotation.Nonnull
  private Integer maxTimeoutSeconds;

  public static final String JSON_PROPERTY_ASSET = "asset";
  @jakarta.annotation.Nonnull
  private String asset;

  public static final String JSON_PROPERTY_EXTRA = "extra";
  @jakarta.annotation.Nullable
  private Map<String, Object> extra = new HashMap<>();

  public X402V1PaymentRequirements() { 
  }

  public X402V1PaymentRequirements scheme(@jakarta.annotation.Nonnull SchemeEnum scheme) {
    this.scheme = scheme;
    return this;
  }

  /**
   * The scheme of the payment protocol to use. Currently, the only supported scheme is &#x60;exact&#x60;.
   * @return scheme
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SCHEME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SchemeEnum getScheme() {
    return scheme;
  }


  @JsonProperty(JSON_PROPERTY_SCHEME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScheme(@jakarta.annotation.Nonnull SchemeEnum scheme) {
    this.scheme = scheme;
  }


  public X402V1PaymentRequirements network(@jakarta.annotation.Nonnull NetworkEnum network) {
    this.network = network;
    return this;
  }

  /**
   * The network of the blockchain to send payment on.
   * @return network
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public NetworkEnum getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetwork(@jakarta.annotation.Nonnull NetworkEnum network) {
    this.network = network;
  }


  public X402V1PaymentRequirements maxAmountRequired(@jakarta.annotation.Nonnull String maxAmountRequired) {
    this.maxAmountRequired = maxAmountRequired;
    return this;
  }

  /**
   * The maximum amount required to pay for the resource in atomic units of the payment asset.
   * @return maxAmountRequired
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMaxAmountRequired() {
    return maxAmountRequired;
  }


  @JsonProperty(JSON_PROPERTY_MAX_AMOUNT_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxAmountRequired(@jakarta.annotation.Nonnull String maxAmountRequired) {
    this.maxAmountRequired = maxAmountRequired;
  }


  public X402V1PaymentRequirements resource(@jakarta.annotation.Nonnull String resource) {
    this.resource = resource;
    return this;
  }

  /**
   * The URL of the resource to pay for.
   * @return resource
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResource() {
    return resource;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResource(@jakarta.annotation.Nonnull String resource) {
    this.resource = resource;
  }


  public X402V1PaymentRequirements description(@jakarta.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * A human-readable description of the resource.
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }


  public X402V1PaymentRequirements mimeType(@jakarta.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * The MIME type of the resource response.
   * @return mimeType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MIME_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMimeType() {
    return mimeType;
  }


  @JsonProperty(JSON_PROPERTY_MIME_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMimeType(@jakarta.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
  }


  public X402V1PaymentRequirements outputSchema(@jakarta.annotation.Nullable Map<String, Object> outputSchema) {
    this.outputSchema = outputSchema;
    return this;
  }

  public X402V1PaymentRequirements putOutputSchemaItem(String key, Object outputSchemaItem) {
    if (this.outputSchema == null) {
      this.outputSchema = new HashMap<>();
    }
    this.outputSchema.put(key, outputSchemaItem);
    return this;
  }

  /**
   * The optional JSON schema describing the resource output.
   * @return outputSchema
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OUTPUT_SCHEMA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getOutputSchema() {
    return outputSchema;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT_SCHEMA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputSchema(@jakarta.annotation.Nullable Map<String, Object> outputSchema) {
    this.outputSchema = outputSchema;
  }


  public X402V1PaymentRequirements payTo(@jakarta.annotation.Nonnull String payTo) {
    this.payTo = payTo;
    return this;
  }

  /**
   * The destination to pay value to.  For EVM networks, payTo will be a 0x-prefixed, checksum EVM address.  For Solana-based networks, payTo will be a base58-encoded Solana address.
   * @return payTo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAY_TO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPayTo() {
    return payTo;
  }


  @JsonProperty(JSON_PROPERTY_PAY_TO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayTo(@jakarta.annotation.Nonnull String payTo) {
    this.payTo = payTo;
  }


  public X402V1PaymentRequirements maxTimeoutSeconds(@jakarta.annotation.Nonnull Integer maxTimeoutSeconds) {
    this.maxTimeoutSeconds = maxTimeoutSeconds;
    return this;
  }

  /**
   * The maximum time in seconds for the resource server to respond.
   * @return maxTimeoutSeconds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAX_TIMEOUT_SECONDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getMaxTimeoutSeconds() {
    return maxTimeoutSeconds;
  }


  @JsonProperty(JSON_PROPERTY_MAX_TIMEOUT_SECONDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxTimeoutSeconds(@jakarta.annotation.Nonnull Integer maxTimeoutSeconds) {
    this.maxTimeoutSeconds = maxTimeoutSeconds;
  }


  public X402V1PaymentRequirements asset(@jakarta.annotation.Nonnull String asset) {
    this.asset = asset;
    return this;
  }

  /**
   * The asset to pay with.  For EVM networks, the asset will be a 0x-prefixed, checksum EVM address.  For Solana-based networks, the asset will be a base58-encoded Solana address.
   * @return asset
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAsset() {
    return asset;
  }


  @JsonProperty(JSON_PROPERTY_ASSET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAsset(@jakarta.annotation.Nonnull String asset) {
    this.asset = asset;
  }


  public X402V1PaymentRequirements extra(@jakarta.annotation.Nullable Map<String, Object> extra) {
    this.extra = extra;
    return this;
  }

  public X402V1PaymentRequirements putExtraItem(String key, Object extraItem) {
    if (this.extra == null) {
      this.extra = new HashMap<>();
    }
    this.extra.put(key, extraItem);
    return this;
  }

  /**
   * The optional additional scheme-specific payment info.
   * @return extra
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTRA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getExtra() {
    return extra;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtra(@jakarta.annotation.Nullable Map<String, Object> extra) {
    this.extra = extra;
  }


  /**
   * Return true if this x402V1PaymentRequirements object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X402V1PaymentRequirements x402V1PaymentRequirements = (X402V1PaymentRequirements) o;
    return Objects.equals(this.scheme, x402V1PaymentRequirements.scheme) &&
        Objects.equals(this.network, x402V1PaymentRequirements.network) &&
        Objects.equals(this.maxAmountRequired, x402V1PaymentRequirements.maxAmountRequired) &&
        Objects.equals(this.resource, x402V1PaymentRequirements.resource) &&
        Objects.equals(this.description, x402V1PaymentRequirements.description) &&
        Objects.equals(this.mimeType, x402V1PaymentRequirements.mimeType) &&
        Objects.equals(this.outputSchema, x402V1PaymentRequirements.outputSchema) &&
        Objects.equals(this.payTo, x402V1PaymentRequirements.payTo) &&
        Objects.equals(this.maxTimeoutSeconds, x402V1PaymentRequirements.maxTimeoutSeconds) &&
        Objects.equals(this.asset, x402V1PaymentRequirements.asset) &&
        Objects.equals(this.extra, x402V1PaymentRequirements.extra);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheme, network, maxAmountRequired, resource, description, mimeType, outputSchema, payTo, maxTimeoutSeconds, asset, extra);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X402V1PaymentRequirements {\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    maxAmountRequired: ").append(toIndentedString(maxAmountRequired)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    outputSchema: ").append(toIndentedString(outputSchema)).append("\n");
    sb.append("    payTo: ").append(toIndentedString(payTo)).append("\n");
    sb.append("    maxTimeoutSeconds: ").append(toIndentedString(maxTimeoutSeconds)).append("\n");
    sb.append("    asset: ").append(toIndentedString(asset)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `scheme` to the URL query string
    if (getScheme() != null) {
      joiner.add(String.format("%sscheme%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getScheme()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNetwork()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `maxAmountRequired` to the URL query string
    if (getMaxAmountRequired() != null) {
      joiner.add(String.format("%smaxAmountRequired%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaxAmountRequired()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `resource` to the URL query string
    if (getResource() != null) {
      joiner.add(String.format("%sresource%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getResource()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDescription()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `mimeType` to the URL query string
    if (getMimeType() != null) {
      joiner.add(String.format("%smimeType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMimeType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `outputSchema` to the URL query string
    if (getOutputSchema() != null) {
      for (String _key : getOutputSchema().keySet()) {
        joiner.add(String.format("%soutputSchema%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getOutputSchema().get(_key), URLEncoder.encode(ApiClient.valueToString(getOutputSchema().get(_key)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `payTo` to the URL query string
    if (getPayTo() != null) {
      joiner.add(String.format("%spayTo%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayTo()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `maxTimeoutSeconds` to the URL query string
    if (getMaxTimeoutSeconds() != null) {
      joiner.add(String.format("%smaxTimeoutSeconds%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getMaxTimeoutSeconds()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `asset` to the URL query string
    if (getAsset() != null) {
      joiner.add(String.format("%sasset%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getAsset()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `extra` to the URL query string
    if (getExtra() != null) {
      for (String _key : getExtra().keySet()) {
        joiner.add(String.format("%sextra%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getExtra().get(_key), URLEncoder.encode(ApiClient.valueToString(getExtra().get(_key)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private X402V1PaymentRequirements instance;

    public Builder() {
      this(new X402V1PaymentRequirements());
    }

    protected Builder(X402V1PaymentRequirements instance) {
      this.instance = instance;
    }

    public X402V1PaymentRequirements.Builder scheme(SchemeEnum scheme) {
      this.instance.scheme = scheme;
      return this;
    }
    public X402V1PaymentRequirements.Builder network(NetworkEnum network) {
      this.instance.network = network;
      return this;
    }
    public X402V1PaymentRequirements.Builder maxAmountRequired(String maxAmountRequired) {
      this.instance.maxAmountRequired = maxAmountRequired;
      return this;
    }
    public X402V1PaymentRequirements.Builder resource(String resource) {
      this.instance.resource = resource;
      return this;
    }
    public X402V1PaymentRequirements.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public X402V1PaymentRequirements.Builder mimeType(String mimeType) {
      this.instance.mimeType = mimeType;
      return this;
    }
    public X402V1PaymentRequirements.Builder outputSchema(Map<String, Object> outputSchema) {
      this.instance.outputSchema = outputSchema;
      return this;
    }
    public X402V1PaymentRequirements.Builder payTo(String payTo) {
      this.instance.payTo = payTo;
      return this;
    }
    public X402V1PaymentRequirements.Builder maxTimeoutSeconds(Integer maxTimeoutSeconds) {
      this.instance.maxTimeoutSeconds = maxTimeoutSeconds;
      return this;
    }
    public X402V1PaymentRequirements.Builder asset(String asset) {
      this.instance.asset = asset;
      return this;
    }
    public X402V1PaymentRequirements.Builder extra(Map<String, Object> extra) {
      this.instance.extra = extra;
      return this;
    }


    /**
    * returns a built X402V1PaymentRequirements instance.
    *
    * The builder is not reusable.
    */
    public X402V1PaymentRequirements build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static X402V1PaymentRequirements.Builder builder() {
    return new X402V1PaymentRequirements.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public X402V1PaymentRequirements.Builder toBuilder() {
    return new X402V1PaymentRequirements.Builder()
      .scheme(getScheme())
      .network(getNetwork())
      .maxAmountRequired(getMaxAmountRequired())
      .resource(getResource())
      .description(getDescription())
      .mimeType(getMimeType())
      .outputSchema(getOutputSchema())
      .payTo(getPayTo())
      .maxTimeoutSeconds(getMaxTimeoutSeconds())
      .asset(getAsset())
      .extra(getExtra());
  }

}

