/*
 * Coinbase Developer Platform APIs
 * The Coinbase Developer Platform APIs - leading the world's transition onchain.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: cdp@coinbase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coinbase.cdp.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.coinbase.cdp.openapi.model.X402SettleErrorReason;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.coinbase.cdp.openapi.ApiClient;
/**
 * The result when x402 payment settlement fails.
 */
@JsonPropertyOrder({
  X402SettlePaymentRejection.JSON_PROPERTY_SUCCESS,
  X402SettlePaymentRejection.JSON_PROPERTY_ERROR_REASON,
  X402SettlePaymentRejection.JSON_PROPERTY_ERROR_MESSAGE,
  X402SettlePaymentRejection.JSON_PROPERTY_PAYER,
  X402SettlePaymentRejection.JSON_PROPERTY_TRANSACTION,
  X402SettlePaymentRejection.JSON_PROPERTY_NETWORK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class X402SettlePaymentRejection {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  @jakarta.annotation.Nonnull
  private Boolean success;

  public static final String JSON_PROPERTY_ERROR_REASON = "errorReason";
  @jakarta.annotation.Nonnull
  private X402SettleErrorReason errorReason;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  @jakarta.annotation.Nullable
  private String errorMessage;

  public static final String JSON_PROPERTY_PAYER = "payer";
  @jakarta.annotation.Nullable
  private String payer;

  public static final String JSON_PROPERTY_TRANSACTION = "transaction";
  @jakarta.annotation.Nullable
  private String transaction;

  public static final String JSON_PROPERTY_NETWORK = "network";
  @jakarta.annotation.Nullable
  private String network;

  public X402SettlePaymentRejection() { 
  }

  public X402SettlePaymentRejection success(@jakarta.annotation.Nonnull Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Indicates whether the payment settlement is successful.
   * @return success
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSuccess(@jakarta.annotation.Nonnull Boolean success) {
    this.success = success;
  }


  public X402SettlePaymentRejection errorReason(@jakarta.annotation.Nonnull X402SettleErrorReason errorReason) {
    this.errorReason = errorReason;
    return this;
  }

  /**
   * Get errorReason
   * @return errorReason
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERROR_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public X402SettleErrorReason getErrorReason() {
    return errorReason;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrorReason(@jakarta.annotation.Nonnull X402SettleErrorReason errorReason) {
    this.errorReason = errorReason;
  }


  public X402SettlePaymentRejection errorMessage(@jakarta.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * The message describing the error reason.
   * @return errorMessage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(@jakarta.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public X402SettlePaymentRejection payer(@jakarta.annotation.Nullable String payer) {
    this.payer = payer;
    return this;
  }

  /**
   * The onchain address of the client that is paying for the resource.  For EVM networks, the payer will be a 0x-prefixed, checksum EVM address.  For Solana-based networks, the payer will be a base58-encoded Solana address.
   * @return payer
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPayer() {
    return payer;
  }


  @JsonProperty(JSON_PROPERTY_PAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayer(@jakarta.annotation.Nullable String payer) {
    this.payer = payer;
  }


  public X402SettlePaymentRejection transaction(@jakarta.annotation.Nullable String transaction) {
    this.transaction = transaction;
    return this;
  }

  /**
   * The transaction of the settlement. For EVM networks, the transaction will be a 0x-prefixed, EVM transaction hash. For Solana-based networks, the transaction will be a base58-encoded Solana signature.
   * @return transaction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTransaction() {
    return transaction;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransaction(@jakarta.annotation.Nullable String transaction) {
    this.transaction = transaction;
  }


  public X402SettlePaymentRejection network(@jakarta.annotation.Nullable String network) {
    this.network = network;
    return this;
  }

  /**
   * The network where the settlement occurred.
   * @return network
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetwork(@jakarta.annotation.Nullable String network) {
    this.network = network;
  }


  /**
   * Return true if this x402SettlePaymentRejection object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    X402SettlePaymentRejection x402SettlePaymentRejection = (X402SettlePaymentRejection) o;
    return Objects.equals(this.success, x402SettlePaymentRejection.success) &&
        Objects.equals(this.errorReason, x402SettlePaymentRejection.errorReason) &&
        Objects.equals(this.errorMessage, x402SettlePaymentRejection.errorMessage) &&
        Objects.equals(this.payer, x402SettlePaymentRejection.payer) &&
        Objects.equals(this.transaction, x402SettlePaymentRejection.transaction) &&
        Objects.equals(this.network, x402SettlePaymentRejection.network);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, errorReason, errorMessage, payer, transaction, network);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class X402SettlePaymentRejection {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    errorReason: ").append(toIndentedString(errorReason)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `success` to the URL query string
    if (getSuccess() != null) {
      joiner.add(String.format("%ssuccess%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getSuccess()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `errorReason` to the URL query string
    if (getErrorReason() != null) {
      joiner.add(String.format("%serrorReason%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getErrorReason()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `errorMessage` to the URL query string
    if (getErrorMessage() != null) {
      joiner.add(String.format("%serrorMessage%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getErrorMessage()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `payer` to the URL query string
    if (getPayer() != null) {
      joiner.add(String.format("%spayer%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPayer()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `transaction` to the URL query string
    if (getTransaction() != null) {
      joiner.add(String.format("%stransaction%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getTransaction()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `network` to the URL query string
    if (getNetwork() != null) {
      joiner.add(String.format("%snetwork%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getNetwork()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }

    public static class Builder {

    private X402SettlePaymentRejection instance;

    public Builder() {
      this(new X402SettlePaymentRejection());
    }

    protected Builder(X402SettlePaymentRejection instance) {
      this.instance = instance;
    }

    public X402SettlePaymentRejection.Builder success(Boolean success) {
      this.instance.success = success;
      return this;
    }
    public X402SettlePaymentRejection.Builder errorReason(X402SettleErrorReason errorReason) {
      this.instance.errorReason = errorReason;
      return this;
    }
    public X402SettlePaymentRejection.Builder errorMessage(String errorMessage) {
      this.instance.errorMessage = errorMessage;
      return this;
    }
    public X402SettlePaymentRejection.Builder payer(String payer) {
      this.instance.payer = payer;
      return this;
    }
    public X402SettlePaymentRejection.Builder transaction(String transaction) {
      this.instance.transaction = transaction;
      return this;
    }
    public X402SettlePaymentRejection.Builder network(String network) {
      this.instance.network = network;
      return this;
    }


    /**
    * returns a built X402SettlePaymentRejection instance.
    *
    * The builder is not reusable.
    */
    public X402SettlePaymentRejection build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static X402SettlePaymentRejection.Builder builder() {
    return new X402SettlePaymentRejection.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public X402SettlePaymentRejection.Builder toBuilder() {
    return new X402SettlePaymentRejection.Builder()
      .success(getSuccess())
      .errorReason(getErrorReason())
      .errorMessage(getErrorMessage())
      .payer(getPayer())
      .transaction(getTransaction())
      .network(getNetwork());
  }

}

