# coding: utf-8

"""
    Coinbase Developer Platform APIs

    The Coinbase Developer Platform APIs - leading the world's transition onchain.

    The version of the OpenAPI document: 2.0.0
    Contact: cdp@coinbase.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdp.openapi_client.models.import_end_user_request import ImportEndUserRequest

class TestImportEndUserRequest(unittest.TestCase):
    """ImportEndUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportEndUserRequest:
        """Test ImportEndUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportEndUserRequest`
        """
        model = ImportEndUserRequest()
        if include_optional:
            return ImportEndUserRequest(
                user_id = 'e051beeb-7163-4527-a5b6-35e301529ff2',
                authentication_methods = [{type=email, email=user@example.com}, {type=sms, phoneNumber=+12055555555}, {type=jwt, sub=e051beeb-7163-4527-a5b6-35e301529ff2, kid=NjVBRjY5MDlCMUIwNzU4RTA2QzZFMDQ4QzQ2MDAyQjVDNjk1RTM2Qg}, {type=google, sub=115346410074741490243, email=test.user@gmail.com}],
                encrypted_private_key = 'U2FsdGVkX1+vupppZksvRf5X5YgHq4+da+Q4qf51+Q4=',
                key_type = 'evm'
            )
        else:
            return ImportEndUserRequest(
                user_id = 'e051beeb-7163-4527-a5b6-35e301529ff2',
                authentication_methods = [{type=email, email=user@example.com}, {type=sms, phoneNumber=+12055555555}, {type=jwt, sub=e051beeb-7163-4527-a5b6-35e301529ff2, kid=NjVBRjY5MDlCMUIwNzU4RTA2QzZFMDQ4QzQ2MDAyQjVDNjk1RTM2Qg}, {type=google, sub=115346410074741490243, email=test.user@gmail.com}],
                encrypted_private_key = 'U2FsdGVkX1+vupppZksvRf5X5YgHq4+da+Q4qf51+Q4=',
                key_type = 'evm',
        )
        """

    def testImportEndUserRequest(self):
        """Test ImportEndUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
