package com.coinbase.cdp;

import com.coinbase.cdp.auth.TokenProvider;
import com.coinbase.cdp.http.HttpClientConfig;
import com.coinbase.cdp.http.RetryConfig;
import java.net.http.HttpClient;
import java.util.Optional;
import java.util.function.Consumer;

/**
 * Builder for creating CdpClient instances.
 *
 * <p>Supports two authentication modes:
 *
 * <ul>
 *   <li>API Key credentials - tokens are generated automatically per-request
 *   <li>TokenProvider - use pre-generated tokens (for serverless/edge deployment)
 * </ul>
 *
 * <p>Example with credentials:
 *
 * <pre>{@code
 * CdpClient client = CdpClient.builder()
 *     .credentials("api-key-id", "api-key-secret")
 *     .walletSecret("wallet-secret")
 *     .build();
 * }</pre>
 *
 * <p>Example with TokenProvider:
 *
 * <pre>{@code
 * CdpClient client = CdpClient.builder()
 *     .tokenProvider(myTokenProvider)
 *     .httpConfig(config -> config.debugging(true))
 *     .build();
 * }</pre>
 *
 * <p>Example with HTTP configuration:
 *
 * <pre>{@code
 * CdpClient client = CdpClient.builder()
 *     .credentials("api-key-id", "api-key-secret")
 *     .httpConfig(config -> config
 *         .basePath("https://custom.api.com")
 *         .retryConfig(RetryConfig.builder().maxRetries(5).build())
 *         .debugging(true))
 *     .build();
 * }</pre>
 */
public final class CdpClientBuilder {

  // Authentication (mutually exclusive)
  private String apiKeyId;
  private String apiKeySecret;
  private Optional<String> walletSecret = Optional.empty();
  private TokenProvider tokenProvider;

  // JWT options (only for credential mode)
  private long expiresIn = CdpClientOptions.DEFAULT_EXPIRES_IN;

  // HTTP configuration (shared)
  private String basePath = HttpClientConfig.DEFAULT_BASE_PATH;
  private Optional<RetryConfig> retryConfig = Optional.empty();
  private Optional<HttpClient.Builder> httpClientBuilder = Optional.empty();
  private boolean debugging = false;
  private int maxNetworkRetries = CdpClientOptions.DEFAULT_MAX_RETRIES;

  CdpClientBuilder() {}

  // ==================== Authentication ====================

  /**
   * Sets API key credentials for automatic token generation.
   *
   * @param apiKeyId the API key ID
   * @param apiKeySecret the API key secret (PEM EC key or base64 Ed25519 key)
   * @return this builder
   * @throws IllegalStateException if tokenProvider was already set
   */
  public CdpClientBuilder credentials(String apiKeyId, String apiKeySecret) {
    if (this.tokenProvider != null) {
      throw new IllegalStateException(
          "Cannot set credentials when tokenProvider is already configured. "
              + "Use either credentials() or tokenProvider(), not both.");
    }
    this.apiKeyId = apiKeyId;
    this.apiKeySecret = apiKeySecret;
    return this;
  }

  /**
   * Sets the wallet secret for signing wallet operations.
   *
   * <p>Required for write operations (create account, sign transaction, etc.).
   *
   * @param walletSecret the wallet secret (base64 DER-encoded EC key)
   * @return this builder
   */
  public CdpClientBuilder walletSecret(String walletSecret) {
    this.walletSecret = Optional.ofNullable(walletSecret).filter(s -> !s.isBlank());
    return this;
  }

  /**
   * Sets a pre-generated TokenProvider for authentication.
   *
   * <p>Use this for serverless/edge deployments where tokens are generated by a separate backend
   * service.
   *
   * @param tokenProvider the token provider
   * @return this builder
   * @throws IllegalStateException if credentials were already set
   */
  public CdpClientBuilder tokenProvider(TokenProvider tokenProvider) {
    if (this.apiKeyId != null || this.apiKeySecret != null) {
      throw new IllegalStateException(
          "Cannot set tokenProvider when credentials are already configured. "
              + "Use either credentials() or tokenProvider(), not both.");
    }
    this.tokenProvider = tokenProvider;
    return this;
  }

  // ==================== JWT Configuration ====================

  /**
   * Sets the JWT expiration time in seconds.
   *
   * <p>Only applicable when using credentials (not tokenProvider).
   *
   * @param seconds the expiration time (default: 120 seconds)
   * @return this builder
   */
  public CdpClientBuilder expiresIn(long seconds) {
    this.expiresIn = seconds;
    return this;
  }

  // ==================== HTTP Configuration ====================

  /**
   * Sets the base URL for the CDP API.
   *
   * @param basePath the base URL (default: https://api.cdp.coinbase.com/platform)
   * @return this builder
   */
  public CdpClientBuilder basePath(String basePath) {
    this.basePath = basePath;
    return this;
  }

  /**
   * Sets the retry configuration.
   *
   * @param retryConfig the retry configuration
   * @return this builder
   */
  public CdpClientBuilder retryConfig(RetryConfig retryConfig) {
    this.retryConfig = Optional.ofNullable(retryConfig);
    return this;
  }

  /**
   * Sets the maximum number of network retries.
   *
   * <p>For more advanced retry configuration, use {@link #retryConfig(RetryConfig)} instead.
   *
   * @param maxRetries the maximum number of retries
   * @return this builder
   */
  public CdpClientBuilder maxNetworkRetries(int maxRetries) {
    this.maxNetworkRetries = maxRetries;
    return this;
  }

  /**
   * Sets a custom HttpClient.Builder for HTTP requests.
   *
   * @param httpClientBuilder the HTTP client builder
   * @return this builder
   */
  public CdpClientBuilder httpClientBuilder(HttpClient.Builder httpClientBuilder) {
    this.httpClientBuilder = Optional.ofNullable(httpClientBuilder);
    return this;
  }

  /**
   * Sets whether to enable debug logging.
   *
   * @param debugging true to enable debug logging
   * @return this builder
   */
  public CdpClientBuilder debugging(boolean debugging) {
    this.debugging = debugging;
    return this;
  }

  /**
   * Configures HTTP settings using an HttpClientConfig.
   *
   * @param config the HTTP client configuration
   * @return this builder
   */
  public CdpClientBuilder httpConfig(HttpClientConfig config) {
    this.basePath = config.basePath();
    this.retryConfig = config.retryConfig();
    this.httpClientBuilder = config.httpClientBuilder();
    this.debugging = config.debugging();
    return this;
  }

  /**
   * Configures HTTP settings using a builder callback.
   *
   * <p>Example:
   *
   * <pre>{@code
   * CdpClient.builder()
   *     .credentials(keyId, keySecret)
   *     .httpConfig(config -> config
   *         .debugging(true)
   *         .retryConfig(RetryConfig.builder().maxRetries(5).build()))
   *     .build();
   * }</pre>
   *
   * @param configurer the configuration callback
   * @return this builder
   */
  public CdpClientBuilder httpConfig(Consumer<HttpClientConfig.Builder> configurer) {
    HttpClientConfig.Builder builder = HttpClientConfig.builder();
    configurer.accept(builder);
    return httpConfig(builder.build());
  }

  // ==================== Build ====================

  /**
   * Builds the CdpClient instance.
   *
   * @return a new CdpClient
   * @throws IllegalStateException if neither credentials nor tokenProvider is set
   */
  public CdpClient build() {
    if (tokenProvider != null) {
      return buildWithTokenProvider();
    } else if (apiKeyId != null && apiKeySecret != null) {
      return buildWithCredentials();
    } else {
      throw new IllegalStateException(
          "Either credentials(apiKeyId, apiKeySecret) or tokenProvider(tokens) "
              + "must be configured before calling build().");
    }
  }

  private CdpClient buildWithCredentials() {
    CdpClientOptions options =
        new CdpClientOptions(
            apiKeyId,
            apiKeySecret,
            walletSecret,
            debugging,
            basePath,
            expiresIn,
            maxNetworkRetries,
            retryConfig,
            httpClientBuilder);
    return new CdpClient(options);
  }

  private CdpClient buildWithTokenProvider() {
    HttpClientConfig config =
        new HttpClientConfig(basePath, retryConfig, httpClientBuilder, debugging);
    return new CdpClient(tokenProvider, config);
  }
}
